/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthedBankAccountRouteImport } from './routes/_authed/bank-account'
import { Route as AuthedClientsRouteImport } from './routes/_authed/clients'
import { Route as AuthedCraRouteImport } from './routes/_authed/cra'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDeadlinesRouteImport } from './routes/_authed/deadlines'
import { Route as AuthedDeclarationsRouteImport } from './routes/_authed/declarations'
import { Route as AuthedDocumentsRouteImport } from './routes/_authed/documents'
import { Route as AuthedInvoicesRouteImport } from './routes/_authed/invoices'
import { Route as AuthedReleaseNotesRouteImport } from './routes/_authed/release-notes'
import { Route as AuthedRevenueRouteImport } from './routes/_authed/revenue'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedTreasuryRouteImport } from './routes/_authed/treasury'
import { Route as AuthedWeekRouteImport } from './routes/_authed/week'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as AuthedClientsClientSlugRouteImport } from './routes/_authed/clients_.$clientSlug'
import { Route as AuthedClientsNewRouteImport } from './routes/_authed/clients_.new'
import { Route as AuthedMissionsNewRouteImport } from './routes/_authed/missions_.new'
import { Route as AuthedClientsClientSlugMissionsMissionSlugRouteImport } from './routes/_authed/clients_.$clientSlug_.missions.$missionSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedBankAccountRoute = AuthedBankAccountRouteImport.update({
  id: '/bank-account',
  path: '/bank-account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsRoute = AuthedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCraRoute = AuthedCraRouteImport.update({
  id: '/cra',
  path: '/cra',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeadlinesRoute = AuthedDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeclarationsRoute = AuthedDeclarationsRouteImport.update({
  id: '/declarations',
  path: '/declarations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocumentsRoute = AuthedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesRoute = AuthedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReleaseNotesRoute = AuthedReleaseNotesRouteImport.update({
  id: '/release-notes',
  path: '/release-notes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRevenueRoute = AuthedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTreasuryRoute = AuthedTreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWeekRoute = AuthedWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AuthedRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const AuthedClientsClientSlugRoute = AuthedClientsClientSlugRouteImport.update({
  id: '/clients_/$clientSlug',
  path: '/clients/$clientSlug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsNewRoute = AuthedClientsNewRouteImport.update({
  id: '/clients_/new',
  path: '/clients/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMissionsNewRoute = AuthedMissionsNewRouteImport.update({
  id: '/missions_/new',
  path: '/missions/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsClientSlugMissionsMissionSlugRoute =
  AuthedClientsClientSlugMissionsMissionSlugRouteImport.update({
    id: '/clients_/$clientSlug_/missions/$missionSlug',
    path: '/clients/$clientSlug/missions/$missionSlug',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/bank-account': typeof AuthedBankAccountRoute
  '/clients': typeof AuthedClientsRoute
  '/cra': typeof AuthedCraRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/deadlines': typeof AuthedDeadlinesRoute
  '/declarations': typeof AuthedDeclarationsRoute
  '/documents': typeof AuthedDocumentsRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/release-notes': typeof AuthedReleaseNotesRoute
  '/revenue': typeof AuthedRevenueRoute
  '/settings': typeof AuthedSettingsRoute
  '/treasury': typeof AuthedTreasuryRoute
  '/week': typeof AuthedWeekRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/clients/$clientSlug': typeof AuthedClientsClientSlugRoute
  '/clients/new': typeof AuthedClientsNewRoute
  '/missions/new': typeof AuthedMissionsNewRoute
  '/clients/$clientSlug/missions/$missionSlug': typeof AuthedClientsClientSlugMissionsMissionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/bank-account': typeof AuthedBankAccountRoute
  '/clients': typeof AuthedClientsRoute
  '/cra': typeof AuthedCraRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/deadlines': typeof AuthedDeadlinesRoute
  '/declarations': typeof AuthedDeclarationsRoute
  '/documents': typeof AuthedDocumentsRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/release-notes': typeof AuthedReleaseNotesRoute
  '/revenue': typeof AuthedRevenueRoute
  '/settings': typeof AuthedSettingsRoute
  '/treasury': typeof AuthedTreasuryRoute
  '/week': typeof AuthedWeekRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/clients/$clientSlug': typeof AuthedClientsClientSlugRoute
  '/clients/new': typeof AuthedClientsNewRoute
  '/missions/new': typeof AuthedMissionsNewRoute
  '/clients/$clientSlug/missions/$missionSlug': typeof AuthedClientsClientSlugMissionsMissionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/health': typeof HealthRoute
  '/_authed/bank-account': typeof AuthedBankAccountRoute
  '/_authed/clients': typeof AuthedClientsRoute
  '/_authed/cra': typeof AuthedCraRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/deadlines': typeof AuthedDeadlinesRoute
  '/_authed/declarations': typeof AuthedDeclarationsRoute
  '/_authed/documents': typeof AuthedDocumentsRoute
  '/_authed/invoices': typeof AuthedInvoicesRoute
  '/_authed/release-notes': typeof AuthedReleaseNotesRoute
  '/_authed/revenue': typeof AuthedRevenueRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/treasury': typeof AuthedTreasuryRoute
  '/_authed/week': typeof AuthedWeekRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_authed/clients_/$clientSlug': typeof AuthedClientsClientSlugRoute
  '/_authed/clients_/new': typeof AuthedClientsNewRoute
  '/_authed/missions_/new': typeof AuthedMissionsNewRoute
  '/_authed/clients_/$clientSlug_/missions/$missionSlug': typeof AuthedClientsClientSlugMissionsMissionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/bank-account'
    | '/clients'
    | '/cra'
    | '/dashboard'
    | '/deadlines'
    | '/declarations'
    | '/documents'
    | '/invoices'
    | '/release-notes'
    | '/revenue'
    | '/settings'
    | '/treasury'
    | '/week'
    | '/login'
    | '/register'
    | '/clients/$clientSlug'
    | '/clients/new'
    | '/missions/new'
    | '/clients/$clientSlug/missions/$missionSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/bank-account'
    | '/clients'
    | '/cra'
    | '/dashboard'
    | '/deadlines'
    | '/declarations'
    | '/documents'
    | '/invoices'
    | '/release-notes'
    | '/revenue'
    | '/settings'
    | '/treasury'
    | '/week'
    | '/login'
    | '/register'
    | '/clients/$clientSlug'
    | '/clients/new'
    | '/missions/new'
    | '/clients/$clientSlug/missions/$missionSlug'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_guest'
    | '/health'
    | '/_authed/bank-account'
    | '/_authed/clients'
    | '/_authed/cra'
    | '/_authed/dashboard'
    | '/_authed/deadlines'
    | '/_authed/declarations'
    | '/_authed/documents'
    | '/_authed/invoices'
    | '/_authed/release-notes'
    | '/_authed/revenue'
    | '/_authed/settings'
    | '/_authed/treasury'
    | '/_authed/week'
    | '/_guest/login'
    | '/_guest/register'
    | '/_authed/clients_/$clientSlug'
    | '/_authed/clients_/new'
    | '/_authed/missions_/new'
    | '/_authed/clients_/$clientSlug_/missions/$missionSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  HealthRoute: typeof HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/bank-account': {
      id: '/_authed/bank-account'
      path: '/bank-account'
      fullPath: '/bank-account'
      preLoaderRoute: typeof AuthedBankAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients': {
      id: '/_authed/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthedClientsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cra': {
      id: '/_authed/cra'
      path: '/cra'
      fullPath: '/cra'
      preLoaderRoute: typeof AuthedCraRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deadlines': {
      id: '/_authed/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof AuthedDeadlinesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/declarations': {
      id: '/_authed/declarations'
      path: '/declarations'
      fullPath: '/declarations'
      preLoaderRoute: typeof AuthedDeclarationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/documents': {
      id: '/_authed/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthedDocumentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices': {
      id: '/_authed/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthedInvoicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/release-notes': {
      id: '/_authed/release-notes'
      path: '/release-notes'
      fullPath: '/release-notes'
      preLoaderRoute: typeof AuthedReleaseNotesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/revenue': {
      id: '/_authed/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthedRevenueRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/treasury': {
      id: '/_authed/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof AuthedTreasuryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/week': {
      id: '/_authed/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AuthedWeekRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authed/clients_/$clientSlug': {
      id: '/_authed/clients_/$clientSlug'
      path: '/clients/$clientSlug'
      fullPath: '/clients/$clientSlug'
      preLoaderRoute: typeof AuthedClientsClientSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients_/new': {
      id: '/_authed/clients_/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthedClientsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/missions_/new': {
      id: '/_authed/missions_/new'
      path: '/missions/new'
      fullPath: '/missions/new'
      preLoaderRoute: typeof AuthedMissionsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients_/$clientSlug_/missions/$missionSlug': {
      id: '/_authed/clients_/$clientSlug_/missions/$missionSlug'
      path: '/clients/$clientSlug/missions/$missionSlug'
      fullPath: '/clients/$clientSlug/missions/$missionSlug'
      preLoaderRoute: typeof AuthedClientsClientSlugMissionsMissionSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBankAccountRoute: typeof AuthedBankAccountRoute
  AuthedClientsRoute: typeof AuthedClientsRoute
  AuthedCraRoute: typeof AuthedCraRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDeadlinesRoute: typeof AuthedDeadlinesRoute
  AuthedDeclarationsRoute: typeof AuthedDeclarationsRoute
  AuthedDocumentsRoute: typeof AuthedDocumentsRoute
  AuthedInvoicesRoute: typeof AuthedInvoicesRoute
  AuthedReleaseNotesRoute: typeof AuthedReleaseNotesRoute
  AuthedRevenueRoute: typeof AuthedRevenueRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTreasuryRoute: typeof AuthedTreasuryRoute
  AuthedWeekRoute: typeof AuthedWeekRoute
  AuthedClientsClientSlugRoute: typeof AuthedClientsClientSlugRoute
  AuthedClientsNewRoute: typeof AuthedClientsNewRoute
  AuthedMissionsNewRoute: typeof AuthedMissionsNewRoute
  AuthedClientsClientSlugMissionsMissionSlugRoute: typeof AuthedClientsClientSlugMissionsMissionSlugRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBankAccountRoute: AuthedBankAccountRoute,
  AuthedClientsRoute: AuthedClientsRoute,
  AuthedCraRoute: AuthedCraRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDeadlinesRoute: AuthedDeadlinesRoute,
  AuthedDeclarationsRoute: AuthedDeclarationsRoute,
  AuthedDocumentsRoute: AuthedDocumentsRoute,
  AuthedInvoicesRoute: AuthedInvoicesRoute,
  AuthedReleaseNotesRoute: AuthedReleaseNotesRoute,
  AuthedRevenueRoute: AuthedRevenueRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTreasuryRoute: AuthedTreasuryRoute,
  AuthedWeekRoute: AuthedWeekRoute,
  AuthedClientsClientSlugRoute: AuthedClientsClientSlugRoute,
  AuthedClientsNewRoute: AuthedClientsNewRoute,
  AuthedMissionsNewRoute: AuthedMissionsNewRoute,
  AuthedClientsClientSlugMissionsMissionSlugRoute:
    AuthedClientsClientSlugMissionsMissionSlugRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  HealthRoute: HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
