// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ArchiveClientData, ArchiveClientErrors, ArchiveClientResponses, CreateClientData2, CreateClientErrors, CreateClientResponses, CreateMissionData2, CreateMissionErrors, CreateMissionResponses, CurrentUserData, CurrentUserErrors, CurrentUserResponses, DeleteClientData, DeleteClientErrors, DeleteClientResponses, DeleteMissionData, DeleteMissionErrors, DeleteMissionResponses, GetPingData, GetPingResponses, ListClientsData, ListClientsErrors, ListClientsResponses, LoginData2, LoginErrors, LoginResponses, LogoutData, LogoutErrors, LogoutResponses, RegisterData, RegisterResponses, UnarchiveClientData, UnarchiveClientErrors, UnarchiveClientResponses, UpdateClientData2, UpdateClientErrors, UpdateClientResponses, UpdateMissionData2, UpdateMissionErrors, UpdateMissionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getPing = <ThrowOnError extends boolean = false>(options?: Options<GetPingData, ThrowOnError>): RequestResult<GetPingResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetPingResponses, unknown, ThrowOnError>({ url: '/ping', ...options });

export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, unknown, ThrowOnError> => (options.client ?? client).post<RegisterResponses, unknown, ThrowOnError>({
    url: '/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData2, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, LogoutErrors, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'opusline-session',
            type: 'apiKey'
        }],
    url: '/logout',
    ...options
});

export const currentUser = <ThrowOnError extends boolean = false>(options?: Options<CurrentUserData, ThrowOnError>): RequestResult<CurrentUserResponses, CurrentUserErrors, ThrowOnError> => (options?.client ?? client).get<CurrentUserResponses, CurrentUserErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'opusline-session',
            type: 'apiKey'
        }],
    url: '/user',
    ...options
});

export const listClients = <ThrowOnError extends boolean = false>(options?: Options<ListClientsData, ThrowOnError>): RequestResult<ListClientsResponses, ListClientsErrors, ThrowOnError> => (options?.client ?? client).get<ListClientsResponses, ListClientsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'opusline-session',
            type: 'apiKey'
        }],
    url: '/clients',
    ...options
});

export const createClient = <ThrowOnError extends boolean = false>(options: Options<CreateClientData2, ThrowOnError>): RequestResult<CreateClientResponses, CreateClientErrors, ThrowOnError> => (options.client ?? client).post<CreateClientResponses, CreateClientErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'opusline-session',
            type: 'apiKey'
        }],
    url: '/clients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteClient = <ThrowOnError extends boolean = false>(options: Options<DeleteClientData, ThrowOnError>): RequestResult<DeleteClientResponses, DeleteClientErrors, ThrowOnError> => (options.client ?? client).delete<DeleteClientResponses, DeleteClientErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'opusline-session',
            type: 'apiKey'
        }],
    url: '/clients/{client}',
    ...options
});

export const updateClient = <ThrowOnError extends boolean = false>(options: Options<UpdateClientData2, ThrowOnError>): RequestResult<UpdateClientResponses, UpdateClientErrors, ThrowOnError> => (options.client ?? client).put<UpdateClientResponses, UpdateClientErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'opusline-session',
            type: 'apiKey'
        }],
    url: '/clients/{client}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const archiveClient = <ThrowOnError extends boolean = false>(options: Options<ArchiveClientData, ThrowOnError>): RequestResult<ArchiveClientResponses, ArchiveClientErrors, ThrowOnError> => (options.client ?? client).post<ArchiveClientResponses, ArchiveClientErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'opusline-session',
            type: 'apiKey'
        }],
    url: '/clients/{client}/archive',
    ...options
});

export const unarchiveClient = <ThrowOnError extends boolean = false>(options: Options<UnarchiveClientData, ThrowOnError>): RequestResult<UnarchiveClientResponses, UnarchiveClientErrors, ThrowOnError> => (options.client ?? client).post<UnarchiveClientResponses, UnarchiveClientErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'opusline-session',
            type: 'apiKey'
        }],
    url: '/clients/{client}/unarchive',
    ...options
});

export const createMission = <ThrowOnError extends boolean = false>(options: Options<CreateMissionData2, ThrowOnError>): RequestResult<CreateMissionResponses, CreateMissionErrors, ThrowOnError> => (options.client ?? client).post<CreateMissionResponses, CreateMissionErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'opusline-session',
            type: 'apiKey'
        }],
    url: '/clients/{client}/missions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteMission = <ThrowOnError extends boolean = false>(options: Options<DeleteMissionData, ThrowOnError>): RequestResult<DeleteMissionResponses, DeleteMissionErrors, ThrowOnError> => (options.client ?? client).delete<DeleteMissionResponses, DeleteMissionErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'opusline-session',
            type: 'apiKey'
        }],
    url: '/clients/{client}/missions/{mission}',
    ...options
});

export const updateMission = <ThrowOnError extends boolean = false>(options: Options<UpdateMissionData2, ThrowOnError>): RequestResult<UpdateMissionResponses, UpdateMissionErrors, ThrowOnError> => (options.client ?? client).put<UpdateMissionResponses, UpdateMissionErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'opusline-session',
            type: 'apiKey'
        }],
    url: '/clients/{client}/missions/{mission}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
