// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost/api' | (string & {});
};

/**
 * BillingMode
 */
export type BillingMode = 0 | 1;

/**
 * ClientData
 */
export type ClientData = {
    id: number;
    slug: string;
    name: string;
    notes: string | null;
    archivedAt: string | null;
    missions: Array<MissionData>;
};

/**
 * ClientListData
 */
export type ClientListData = {
    clients: Array<ClientData>;
};

/**
 * CreateClientData
 */
export type CreateClientData = {
    name: string;
    notes?: string | null;
};

/**
 * CreateMissionData
 */
export type CreateMissionData = {
    name: string;
    billingMode: BillingMode;
    rate?: {
        amount: number;
        currency: Currency;
    } | null;
    endClientId?: number | null;
    startDate?: string | null;
    endDate?: string | null;
};

/**
 * Currency
 */
export type Currency = 'EUR';

/**
 * LoginData
 */
export type LoginData = {
    email: string;
    password: string;
    remember?: boolean;
};

/**
 * MissionData
 */
export type MissionData = {
    id: number;
    slug: string;
    clientId: number;
    endClientId: number | null;
    name: string;
    billingMode: BillingMode;
    rate: MoneyData | null;
    status: MissionStatus;
    startDate: string | null;
    endDate: string | null;
};

/**
 * MissionStatus
 */
export type MissionStatus = 0 | 1 | 2;

/**
 * MoneyData
 */
export type MoneyData = {
    amount: number;
    currency: Currency;
};

/**
 * RegisterUserData
 */
export type RegisterUserData = {
    name: string;
    email: string;
    password: string;
    password_confirmation: string;
};

/**
 * UpdateClientData
 */
export type UpdateClientData = {
    name: string;
    notes?: string | null;
};

/**
 * UpdateMissionData
 */
export type UpdateMissionData = {
    name: string;
    status: MissionStatus;
    rate?: {
        amount: number;
        currency: Currency;
    } | null;
    endClientId?: number | null;
    startDate?: string | null;
    endDate?: string | null;
};

/**
 * UserData
 */
export type UserData = {
    id: number;
    name: string;
    email: string;
};

export type GetPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ping';
};

export type GetPingResponses = {
    200: {
        status: 'ok';
        version: string;
    };
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];

export type RegisterData = {
    body: RegisterUserData;
    path?: never;
    query?: never;
    url: '/register';
};

export type RegisterResponses = {
    201: UserData;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData2 = {
    body: LoginData;
    path?: never;
    query?: never;
    url: '/login';
};

export type LoginErrors = {
    /**
     * An error
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    200: UserData;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type LogoutErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * No content
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type CurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type CurrentUserErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type CurrentUserError = CurrentUserErrors[keyof CurrentUserErrors];

export type CurrentUserResponses = {
    200: UserData;
};

export type CurrentUserResponse = CurrentUserResponses[keyof CurrentUserResponses];

export type ListClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clients';
};

export type ListClientsErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ListClientsError = ListClientsErrors[keyof ListClientsErrors];

export type ListClientsResponses = {
    200: ClientListData;
};

export type ListClientsResponse = ListClientsResponses[keyof ListClientsResponses];

export type CreateClientData2 = {
    body: CreateClientData;
    path?: never;
    query?: never;
    url: '/clients';
};

export type CreateClientErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type CreateClientError = CreateClientErrors[keyof CreateClientErrors];

export type CreateClientResponses = {
    201: ClientData;
};

export type CreateClientResponse = CreateClientResponses[keyof CreateClientResponses];

export type DeleteClientData = {
    body?: never;
    path: {
        /**
         * The client ID
         */
        client: number;
    };
    query?: never;
    url: '/clients/{client}';
};

export type DeleteClientErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * An error
     */
    409: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type DeleteClientError = DeleteClientErrors[keyof DeleteClientErrors];

export type DeleteClientResponses = {
    /**
     * No content
     */
    204: void;
};

export type DeleteClientResponse = DeleteClientResponses[keyof DeleteClientResponses];

export type UpdateClientData2 = {
    body: UpdateClientData;
    path: {
        /**
         * The client ID
         */
        client: number;
    };
    query?: never;
    url: '/clients/{client}';
};

export type UpdateClientErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type UpdateClientError = UpdateClientErrors[keyof UpdateClientErrors];

export type UpdateClientResponses = {
    200: ClientData;
};

export type UpdateClientResponse = UpdateClientResponses[keyof UpdateClientResponses];

export type ArchiveClientData = {
    body?: never;
    path: {
        /**
         * The client ID
         */
        client: number;
    };
    query?: never;
    url: '/clients/{client}/archive';
};

export type ArchiveClientErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ArchiveClientError = ArchiveClientErrors[keyof ArchiveClientErrors];

export type ArchiveClientResponses = {
    200: ClientData;
};

export type ArchiveClientResponse = ArchiveClientResponses[keyof ArchiveClientResponses];

export type UnarchiveClientData = {
    body?: never;
    path: {
        /**
         * The client ID
         */
        client: number;
    };
    query?: never;
    url: '/clients/{client}/unarchive';
};

export type UnarchiveClientErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type UnarchiveClientError = UnarchiveClientErrors[keyof UnarchiveClientErrors];

export type UnarchiveClientResponses = {
    200: ClientData;
};

export type UnarchiveClientResponse = UnarchiveClientResponses[keyof UnarchiveClientResponses];

export type CreateMissionData2 = {
    body: CreateMissionData;
    path: {
        /**
         * The client ID
         */
        client: number;
    };
    query?: never;
    url: '/clients/{client}/missions';
};

export type CreateMissionErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type CreateMissionError = CreateMissionErrors[keyof CreateMissionErrors];

export type CreateMissionResponses = {
    201: MissionData;
};

export type CreateMissionResponse = CreateMissionResponses[keyof CreateMissionResponses];

export type DeleteMissionData = {
    body?: never;
    path: {
        /**
         * The client ID
         */
        client: number;
        /**
         * The mission ID
         */
        mission: number;
    };
    query?: never;
    url: '/clients/{client}/missions/{mission}';
};

export type DeleteMissionErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type DeleteMissionError = DeleteMissionErrors[keyof DeleteMissionErrors];

export type DeleteMissionResponses = {
    /**
     * No content
     */
    204: void;
};

export type DeleteMissionResponse = DeleteMissionResponses[keyof DeleteMissionResponses];

export type UpdateMissionData2 = {
    body: UpdateMissionData;
    path: {
        /**
         * The client ID
         */
        client: number;
        /**
         * The mission ID
         */
        mission: number;
    };
    query?: never;
    url: '/clients/{client}/missions/{mission}';
};

export type UpdateMissionErrors = {
    /**
     * Unauthenticated
     */
    401: {
        /**
         * Error overview.
         */
        message: string;
    };
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type UpdateMissionError = UpdateMissionErrors[keyof UpdateMissionErrors];

export type UpdateMissionResponses = {
    200: MissionData;
};

export type UpdateMissionResponse = UpdateMissionResponses[keyof UpdateMissionResponses];
