// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

/**
 * LoginData
 */
export const zLoginData = z.object({
    email: z.email(),
    password: z.string().check(z.minLength(1)),
    remember: z.optional(z.boolean())
});

/**
 * RegisterUserData
 */
export const zRegisterUserData = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(255)),
    email: z.email().check(z.maxLength(255)),
    password: z.string().check(z.minLength(8)),
    password_confirmation: z.string().check(z.minLength(8))
});

/**
 * UserData
 */
export const zUserData = z.object({
    id: z.int(),
    name: z.string(),
    email: z.string()
});

export const zGetPingResponse = z.object({
    status: z.literal('ok'),
    version: z.string()
});

export const zRegisterBody = zRegisterUserData;

export const zRegisterResponse = zUserData;

export const zLoginBody = zLoginData;

export const zLoginResponse = zUserData;

/**
 * No content
 */
export const zLogoutResponse = z.void();

export const zCurrentUserResponse = zUserData;
