// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

/**
 * BillingMode
 */
export const zBillingMode = z.union([z.literal(0), z.literal(1)]);

/**
 * CreateClientData
 */
export const zCreateClientData = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(255)),
    notes: z.nullish(z.string())
});

/**
 * Currency
 */
export const zCurrency = z.enum(['EUR']);

/**
 * CreateMissionData
 */
export const zCreateMissionData = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(255)),
    billingMode: zBillingMode,
    rate: z.nullish(z.object({
        amount: z.int().check(z.gte(1)),
        currency: zCurrency
    })),
    endClientId: z.nullish(z.int()),
    startDate: z.nullish(z.iso.date()),
    endDate: z.nullish(z.iso.date())
});

/**
 * LoginData
 */
export const zLoginData = z.object({
    email: z.email(),
    password: z.string().check(z.minLength(1)),
    remember: z.optional(z.boolean())
});

/**
 * MissionStatus
 */
export const zMissionStatus = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * MoneyData
 */
export const zMoneyData = z.object({
    amount: z.int(),
    currency: zCurrency
});

/**
 * MissionData
 */
export const zMissionData = z.object({
    id: z.int(),
    slug: z.string(),
    clientId: z.int(),
    endClientId: z.nullable(z.int()),
    name: z.string(),
    billingMode: zBillingMode,
    rate: z.nullable(zMoneyData),
    status: zMissionStatus,
    startDate: z.nullable(z.iso.datetime()),
    endDate: z.nullable(z.iso.datetime())
});

/**
 * ClientData
 */
export const zClientData = z.object({
    id: z.int(),
    slug: z.string(),
    name: z.string(),
    notes: z.nullable(z.string()),
    archivedAt: z.nullable(z.iso.datetime()),
    missions: z.array(zMissionData)
});

/**
 * ClientListData
 */
export const zClientListData = z.object({
    clients: z.array(zClientData)
});

/**
 * RegisterUserData
 */
export const zRegisterUserData = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(255)),
    email: z.email().check(z.maxLength(255)),
    password: z.string().check(z.minLength(8)),
    password_confirmation: z.string().check(z.minLength(8))
});

/**
 * UpdateClientData
 */
export const zUpdateClientData = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(255)),
    notes: z.nullish(z.string())
});

/**
 * UpdateMissionData
 */
export const zUpdateMissionData = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(255)),
    status: zMissionStatus,
    rate: z.nullish(z.object({
        amount: z.int().check(z.gte(1)),
        currency: zCurrency
    })),
    endClientId: z.nullish(z.int()),
    startDate: z.nullish(z.iso.date()),
    endDate: z.nullish(z.iso.date())
});

/**
 * UserData
 */
export const zUserData = z.object({
    id: z.int(),
    name: z.string(),
    email: z.string()
});

export const zGetPingResponse = z.object({
    status: z.literal('ok'),
    version: z.string()
});

export const zRegisterBody = zRegisterUserData;

export const zRegisterResponse = zUserData;

export const zLoginBody = zLoginData;

export const zLoginResponse = zUserData;

/**
 * No content
 */
export const zLogoutResponse = z.void();

export const zCurrentUserResponse = zUserData;

export const zListClientsResponse = zClientListData;

export const zCreateClientBody = zCreateClientData;

export const zCreateClientResponse = zClientData;

export const zDeleteClientPath = z.object({
    client: z.int()
});

/**
 * No content
 */
export const zDeleteClientResponse = z.void();

export const zUpdateClientBody = zUpdateClientData;

export const zUpdateClientPath = z.object({
    client: z.int()
});

export const zUpdateClientResponse = zClientData;

export const zArchiveClientPath = z.object({
    client: z.int()
});

export const zArchiveClientResponse = zClientData;

export const zUnarchiveClientPath = z.object({
    client: z.int()
});

export const zUnarchiveClientResponse = zClientData;

export const zCreateMissionBody = zCreateMissionData;

export const zCreateMissionPath = z.object({
    client: z.int()
});

export const zCreateMissionResponse = zMissionData;

export const zDeleteMissionPath = z.object({
    client: z.int(),
    mission: z.int()
});

/**
 * No content
 */
export const zDeleteMissionResponse = z.void();

export const zUpdateMissionBody = zUpdateMissionData;

export const zUpdateMissionPath = z.object({
    client: z.int(),
    mission: z.int()
});

export const zUpdateMissionResponse = zMissionData;
