// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

/**
 * BackupRecordData
 */
export const zBackupRecordData = z.object({
    takenAt: z.iso.datetime(),
    archive: z.string(),
    bytes: z.int()
});

/**
 * BankBalanceSource
 *
 * | |
 * |---|
 * | `0` <br/>  |
 * | `1` <br/>  |
 * | `2` <br/> No anchor exists: the balance is the sum of every imported movement, as if the account had opened empty just before the first one. Exact once the full history is imported; the hand-typed anchor corrects it otherwise. |
 */
export const zBankBalanceSource = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * BankMatchInvoiceData
 */
export const zBankMatchInvoiceData = z.object({
    id: z.int(),
    number: z.nullable(z.string()),
    clientName: z.string()
});

/**
 * BankMatchReason
 *
 * Why a credit movement was paired with an invoice. Ascending value = descending confidence; the matcher offers the lowest value that applies.
 *
 */
export const zBankMatchReason = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * BankMovementExpenseData
 */
export const zBankMovementExpenseData = z.object({
    id: z.int(),
    supplier: z.string()
});

/**
 * BankMovementInvoiceData
 */
export const zBankMovementInvoiceData = z.object({
    id: z.int(),
    number: z.nullable(z.string())
});

/**
 * BankStatementData
 */
export const zBankStatementData = z.object({
    id: z.int(),
    fileName: z.string(),
    periodStart: z.iso.date(),
    periodEnd: z.iso.date(),
    lineCount: z.int(),
    importedAt: z.iso.date(),
    matchCount: z.int(),
    validatedMatchCount: z.int()
});

/**
 * BillingMode
 */
export const zBillingMode = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * CalendarFeedData
 */
export const zCalendarFeedData = z.object({
    invoices: z.boolean(),
    reminders: z.boolean(),
    vat: z.boolean(),
    urssaf: z.boolean(),
    other: z.boolean()
});

/**
 * CancelSubscriptionData
 */
export const zCancelSubscriptionData = z.object({
    cancelledOn: z.nullish(z.iso.date())
});

/**
 * ClientType
 */
export const zClientType = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * Color
 */
export const zColor = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5),
    z.literal(6),
    z.literal(7)
]);

/**
 * ClientData
 */
export const zClientData = z.object({
    id: z.int(),
    slug: z.string(),
    name: z.string(),
    type: zClientType,
    notes: z.nullable(z.string()),
    siret: z.nullable(z.string()),
    vatNumber: z.nullable(z.string()),
    defaultVatRateBp: z.nullable(z.int()),
    billingAddressLine1: z.nullable(z.string()),
    billingAddressLine2: z.nullable(z.string()),
    billingPostalCode: z.nullable(z.string()),
    billingCity: z.nullable(z.string()),
    billingCountry: z.nullable(z.string()),
    billingContactName: z.nullable(z.string()),
    billingEmail: z.nullable(z.string()),
    color: zColor,
    paymentTermsDays: z.int(),
    archivedAt: z.nullable(z.iso.datetime()),
    createdAt: z.iso.datetime()
});

/**
 * ConfirmPasswordData
 */
export const zConfirmPasswordData = z.object({
    password: z.string()
});

/**
 * ConfirmTotpData
 */
export const zConfirmTotpData = z.object({
    code: z.string()
});

/**
 * ContributionLineKind
 *
 * The lines a micro-entrepreneur's URSSAF declaration is settled in, each a rate on the same collected base.
 *
 */
export const zContributionLineKind = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * CorrectInvoiceDatesData
 */
export const zCorrectInvoiceDatesData = z.object({
    issuedOn: z.nullish(z.iso.date()),
    sentOn: z.nullish(z.iso.date()),
    paidOn: z.nullish(z.iso.date())
});

/**
 * CraCountsData
 */
export const zCraCountsData = z.object({
    toProduce: z.int(),
    sent: z.int(),
    signed: z.int()
});

/**
 * CraDayData
 */
export const zCraDayData = z.object({
    date: z.iso.date(),
    dayFractionBp: z.int(),
    trackedDayFractionBp: z.int(),
    isWeekend: z.boolean(),
    isHoliday: z.boolean(),
    holidayName: z.nullable(z.string())
});

/**
 * CraStatus
 */
export const zCraStatus = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * CraListItemData
 */
export const zCraListItemData = z.object({
    id: z.nullable(z.int()),
    missionId: z.int(),
    missionSlug: z.string(),
    missionName: z.string(),
    clientSlug: z.string(),
    clientName: z.string(),
    color: zColor,
    month: z.string(),
    status: zCraStatus,
    totalDays: z.number(),
    trackedDays: z.number()
});

/**
 * CraListData
 */
export const zCraListData = z.object({
    cras: z.array(zCraListItemData),
    counts: zCraCountsData
});

/**
 * CreateClientData
 */
export const zCreateClientData = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(255)),
    type: zClientType,
    notes: z.nullish(z.string().check(z.maxLength(2000))),
    siret: z.nullish(z.string().check(z.maxLength(255))),
    vatNumber: z.nullish(z.string().check(z.maxLength(255))),
    defaultVatRateBp: z.nullish(z.int().check(z.gte(0), z.lte(10000))),
    billingAddressLine1: z.nullish(z.string().check(z.maxLength(255))),
    billingAddressLine2: z.nullish(z.string().check(z.maxLength(255))),
    billingPostalCode: z.nullish(z.string().check(z.maxLength(32))),
    billingCity: z.nullish(z.string().check(z.maxLength(255))),
    billingCountry: z.nullish(z.string().check(z.maxLength(255))),
    billingContactName: z.nullish(z.string().check(z.maxLength(255))),
    billingEmail: z.nullish(z.email().check(z.maxLength(255))),
    color: z.optional(zColor),
    paymentTermsDays: z.optional(z.int().check(z.gte(0), z.lte(365)))
});

/**
 * CreateCraData
 */
export const zCreateCraData = z.object({
    missionId: z.int(),
    month: z.string().check(z.regex(/^(19|20)\d{2}-(0[1-9]|1[0-2])$/))
});

/**
 * Currency
 *
 * The currencies an account can be denominated in. Backed by the ISO 4217 code rather than an int — unlike every other enum here — because the code *is* the identifier the rest of the stack speaks: moneyphp, `Intl.NumberFormat`, and the `char(3)` columns all round-trip it verbatim.  Every case must have an ISO minor unit of 2, because storage is `*_cents` columns and the whole codebase reads them as hundredths. CurrencyTest enforces it, so adding JPY (0 decimals) or TND (3) fails the suite rather than quietly mis-stating amounts by two orders of magnitude.
 *
 */
export const zCurrency = z.enum([
    'EUR',
    'USD',
    'GBP',
    'CHF',
    'CAD',
    'AUD',
    'NZD',
    'SEK',
    'NOK',
    'DKK',
    'PLN',
    'CZK',
    'RON',
    'BGN',
    'SGD',
    'HKD',
    'AED',
    'ILS',
    'INR',
    'BRL',
    'MXN',
    'ZAR',
    'MAD'
]);

/**
 * ChangeSubscriptionAmountData
 */
export const zChangeSubscriptionAmountData = z.object({
    amountHt: z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    }),
    effectiveFrom: z.iso.date()
});

/**
 * CreatePersonalTransferData
 */
export const zCreatePersonalTransferData = z.object({
    amount: z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    }),
    transferredOn: z.iso.date(),
    note: z.nullish(z.string().check(z.maxLength(255)))
});

/**
 * DateFormat
 *
 * The numeric layout calendar dates are displayed in — 31/08/2026 or 2026-08-31. Only digit-only dates follow this preference; weekday and month names follow the account locale.
 *
 */
export const zDateFormat = z.union([z.literal(0), z.literal(1)]);

/**
 * DeadlineItemType
 *
 * What one line of the Échéances timeline is. The order of the cases is also the order two lines sharing a due date sort in: an invoice first, then the relance it calls for, then the fisc.
 *
 */
export const zDeadlineItemType = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * DeclarationCompletionData
 */
export const zDeclarationCompletionData = z.object({
    declaredOn: z.iso.date(),
    paidOn: z.nullable(z.iso.date())
});

/**
 * DeclarationDeadlineData
 */
export const zDeclarationDeadlineData = z.object({
    dueOn: z.iso.date(),
    daysLeft: z.int()
});

/**
 * DismissRecurringDebitData
 */
export const zDismissRecurringDebitData = z.object({
    label: z.string().check(z.minLength(1), z.maxLength(255)),
    amount: z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    })
});

/**
 * DocumentCategory
 *
 * | |
 * |---|
 * | `0` <br/>  |
 * | `1` <br/>  |
 * | `2` <br/>  |
 * | `3` <br/>  |
 * | `4` <br/>  |
 * | `5` <br/> The CRA Opusline generated, filed next to the signed return it comes back as. |
 * | `6` <br/>  |
 * | `7` <br/>  |
 * | `8` <br/>  |
 * | `9` <br/>  |
 * | `10` <br/>  |
 * | `11` <br/> The document the user's billing tool issued, filed against the invoice it is. |
 */
export const zDocumentCategory = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5),
    z.literal(6),
    z.literal(7),
    z.literal(8),
    z.literal(9),
    z.literal(10),
    z.literal(11)
]);

/**
 * DocumentSource
 */
export const zDocumentSource = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * DocumentData
 */
export const zDocumentData = z.object({
    id: z.int(),
    fileName: z.string(),
    category: zDocumentCategory,
    source: zDocumentSource,
    sizeBytes: z.int(),
    createdAt: z.iso.datetime()
});

/**
 * DocumentGroupData
 */
export const zDocumentGroupData = z.object({
    name: z.string(),
    color: zColor,
    clientName: z.string(),
    clientSlug: z.string(),
    missionSlug: z.nullable(z.string()),
    lastAddedAt: z.iso.datetime(),
    documents: z.array(zDocumentData)
});

/**
 * DocumentLibraryData
 */
export const zDocumentLibraryData = z.object({
    groups: z.array(zDocumentGroupData)
});

/**
 * DocumentListData
 */
export const zDocumentListData = z.object({
    documents: z.array(zDocumentData)
});

/**
 * EntryRounding
 *
 * Rounding increment for time entries, expressed as a fraction of the mission's billing unit: half or a quarter of a day/hour, or to the minute.
 *
 */
export const zEntryRounding = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * CreateMissionData
 */
export const zCreateMissionData = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(255)),
    billingMode: zBillingMode,
    rate: z.nullish(z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    })),
    referenceDailyRate: z.nullish(z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    })),
    endClientName: z.nullish(z.string().check(z.minLength(1), z.maxLength(255))),
    rounding: z.nullish(zEntryRounding),
    craRequired: z.nullish(z.boolean()),
    color: z.nullish(zColor),
    notes: z.nullish(z.string().check(z.maxLength(2000))),
    startDate: z.nullish(z.iso.date()),
    endDate: z.nullish(z.iso.date())
});

/**
 * ExpenseBankMovementData
 */
export const zExpenseBankMovementData = z.object({
    id: z.int(),
    bookedOn: z.iso.date(),
    label: z.string()
});

/**
 * ExpenseCategory
 */
export const zExpenseCategory = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5),
    z.literal(6),
    z.literal(7),
    z.literal(8),
    z.literal(9),
    z.literal(10),
    z.literal(11),
    z.literal(12)
]);

/**
 * ExpenseReceiptData
 */
export const zExpenseReceiptData = z.object({
    id: z.int(),
    fileName: z.string(),
    sizeBytes: z.int()
});

/**
 * ExpenseSelectionData
 */
export const zExpenseSelectionData = z.object({
    expenseIds: z.array(z.int()).check(z.minLength(1))
});

/**
 * ExpenseTodoKind
 *
 * The cards of the journal's « À traiter » rail.
 * | |
 * |---|
 * | `0` <br/> A subscription's debit was recorded; the receipt is still to be linked. |
 * | `1` <br/> A debit that names a subscription but that no expense explains. |
 * | `2` <br/> An annual subscription debits within the month. |
 */
export const zExpenseTodoKind = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * ExpenseVatStatus
 *
 * Where a purchase's TVA stands with the CA3. Derived on every read from the receipt, the claim period and the declared months — never stored, so un-marking a declaration honestly flips the rows back.
 * | |
 * |---|
 * | `0` <br/> Receipted and waiting for its CA3 to be declared. |
 * | `1` <br/> Its CA3 was marked declared: the deduction is filed. |
 * | `2` <br/> Claimed on a later CA3 than the purchase month, by choice or because that month was already declared. |
 * | `3` <br/> No receipt: the fisc refuses the deduction until one is attached. |
 * | `4` <br/> Autoliquidation: due and deducted on the same CA3, nothing to recover. |
 * | `5` <br/> Exempt purchase, a receipt whose TVA is not tracked, or an account that files no CA3. |
 */
export const zExpenseVatStatus = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5)
]);

/**
 * ExpenseVatTreatment
 *
 * How the TVA on a purchase reaches the CA3. The receipt decides, never the supplier's country: a foreign SaaS billing through a European entity with 20 % on the invoice is Domestic.
 * | |
 * |---|
 * | `0` <br/> A French invoice carrying TVA at the stated rate. |
 * | `1` <br/> An EU supplier who invoiced without TVA against the intra-community number (autoliquidation). |
 * | `2` <br/> A non-EU supplier who invoiced without TVA (autoliquidation). |
 * | `3` <br/> No TVA at all: insurance, bank fees, stamps, CFE. |
 */
export const zExpenseVatTreatment = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3)
]);

/**
 * ExpenseInputData
 */
export const zExpenseInputData = z.object({
    supplier: z.string().check(z.minLength(1), z.maxLength(120)),
    spentOn: z.iso.date(),
    category: zExpenseCategory,
    amountTtc: z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    }),
    vatTreatment: zExpenseVatTreatment,
    vatRateBp: z.int().check(z.gte(0), z.lte(10000)),
    proShareBp: z.optional(z.int().check(z.gte(0), z.lte(10000))),
    description: z.nullish(z.string().check(z.maxLength(255))),
    subscriptionId: z.nullish(z.int().check(z.gte(1))),
    recurringDebitDay: z.nullish(z.int().check(z.gte(1), z.lte(31)))
});

/**
 * FiscalDeadlineKind
 *
 * The recurring French fiscal deadlines the app tracks. Declaration and payment share a case wherever they share a date, which is every case here: URSSAF télépaie on the declaration date, and the CA3 is due and paid the same day.
 * | |
 * |---|
 * | `0` <br/>  |
 * | `1` <br/>  |
 * | `2` <br/>  |
 * | `3` <br/>  |
 * | `4` <br/>  |
 * | `5` <br/> The 2042-C PRO, keyed by the year of income it declares. |
 */
export const zFiscalDeadlineKind = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5)
]);

/**
 * CompleteDeclarationData
 */
export const zCompleteDeclarationData = z.object({
    kind: zFiscalDeadlineKind,
    periodKey: z.string().check(z.maxLength(16), z.regex(/^\d{4}(-(0[1-9]|1[0-2]|Q[1-4]))?$/)),
    period: z.nullish(z.string().check(z.regex(/^(19|20)\d{2}-(0[1-9]|1[0-2])$/)))
});

/**
 * CompleteFiscalDeadlineData
 */
export const zCompleteFiscalDeadlineData = z.object({
    kind: zFiscalDeadlineKind,
    periodKey: z.string().check(z.maxLength(16), z.regex(/^\d{4}(-(0[1-9]|1[0-2]|Q[1-4]))?$/))
});

/**
 * FixedPriceBudgetState
 *
 * How much of a forfait its tracked time has eaten, as three states rather than a raw percentage: the threshold that separates them is a product decision, and resolving it here keeps every screen — banner, tile, badge, « À traiter » — reading the same one. Labels live on the frontend, like every other enum here.
 *
 */
export const zFixedPriceBudgetState = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * ImportBankStatementData
 */
export const zImportBankStatementData = z.object({
    file: z.string(),
    balanceAmount: z.nullish(z.int()),
    balanceCurrency: z.nullish(zCurrency)
});

/**
 * IncomeTaxReturnBox
 *
 * Where the micro-BNC receipts go on the 2042-C PRO.
 * | |
 * |---|
 * | `0` <br/> Case 5TE — the versement libératoire was opted for; the tax is already paid. |
 * | `1` <br/> Case 5HQ — no option; the receipts join the household's taxable income after the abatement. |
 */
export const zIncomeTaxReturnBox = z.union([z.literal(0), z.literal(1)]);

/**
 * InstanceData
 */
export const zInstanceData = z.object({
    version: z.string(),
    database: z.string(),
    backup: z.nullable(zBackupRecordData)
});

/**
 * InvoiceCountsData
 */
export const zInvoiceCountsData = z.object({
    all: z.int(),
    draft: z.int(),
    sent: z.int(),
    late: z.int(),
    paid: z.int()
});

/**
 * InvoiceEventKind
 */
export const zInvoiceEventKind = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4)
]);

/**
 * InvoiceEventData
 */
export const zInvoiceEventData = z.object({
    id: z.int(),
    kind: zInvoiceEventKind,
    occurredOn: z.iso.date(),
    note: z.nullable(z.string())
});

/**
 * InvoiceForecastBucket
 *
 * The bars of "Attendu sur 60 jours". Money already late is not one of them: it is not expected, it is missing, and it is reported on its own as `overdue`. Keeping it here would both duplicate that figure and scale the bars against a bar nobody draws.
 *
 */
export const zInvoiceForecastBucket = z.union([z.literal(1), z.literal(2)]);

/**
 * InvoiceStatus
 */
export const zInvoiceStatus = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * CreateInvoiceData
 */
export const zCreateInvoiceData = z.object({
    clientId: z.int(),
    amountHt: z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    }),
    missionId: z.nullish(z.int()),
    number: z.nullish(z.string().check(z.minLength(1), z.maxLength(255))),
    status: z.nullish(zInvoiceStatus),
    issuedOn: z.nullish(z.iso.date()),
    dueOn: z.nullish(z.iso.date()),
    paidOn: z.nullish(z.iso.date()),
    periodStart: z.nullish(z.iso.date()),
    periodEnd: z.nullish(z.iso.date()),
    amountTtc: z.nullish(z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    })),
    vatRateBp: z.nullish(z.int().check(z.gte(0), z.lte(10000))),
    notes: z.nullish(z.string().check(z.maxLength(2000))),
    timeEntryIds: z.optional(z.array(z.int()))
});

/**
 * InvoiceTodoKind
 *
 * What the "À traiter" list can put in front of you: money that was billed and has not come in, money that was worked and has not been billed, and a forfait whose time is running out or has already run over. Drafts are not here — an unsent draft is a note to self, not a debt. Labels live on the frontend, like every other enum here.
 *
 */
export const zInvoiceTodoKind = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3)
]);

/**
 * InvoiceTodoOverdueData
 */
export const zInvoiceTodoOverdueData = z.object({
    invoiceId: z.int(),
    number: z.nullable(z.string()),
    dueOn: z.iso.date(),
    daysLate: z.int()
});

/**
 * InvoiceTodoWorkData
 */
export const zInvoiceTodoWorkData = z.object({
    missionId: z.int(),
    missionName: z.string(),
    entryCount: z.int(),
    firstEntryOn: z.iso.date(),
    lastEntryOn: z.iso.date(),
    valuedDays: z.nullable(z.number()),
    valuedMinutes: z.nullable(z.int()),
    timeEntryIds: z.array(z.int()),
    vatRateBp: z.int()
});

/**
 * LinkExpenseBankMovementData
 */
export const zLinkExpenseBankMovementData = z.object({
    bankMovementId: z.int().check(z.gte(1))
});

/**
 * Locale
 */
export const zLocale = z.enum(['en-US', 'fr-FR']);

/**
 * LoginData
 */
export const zLoginData = z.object({
    email: z.email(),
    password: z.string().check(z.minLength(1)),
    remember: z.optional(z.boolean())
});

/**
 * MissionStatus
 */
export const zMissionStatus = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * MoneyData
 */
export const zMoneyData = z.object({
    amount: z.int(),
    currency: zCurrency
});

/**
 * BankMatchData
 */
export const zBankMatchData = z.object({
    id: z.int(),
    reason: zBankMatchReason,
    movementId: z.int(),
    bookedOn: z.iso.date(),
    label: z.string(),
    amount: zMoneyData,
    invoice: zBankMatchInvoiceData
});

/**
 * BankProvisionData
 */
export const zBankProvisionData = z.object({
    amount: zMoneyData,
    carried: zMoneyData,
    rateBp: z.nullable(z.int()),
    deductible: z.nullable(zMoneyData),
    periodEnd: z.iso.date(),
    isEstimate: z.optional(z.boolean())
});

/**
 * BankProvisionsData
 */
export const zBankProvisionsData = z.object({
    vat: z.nullable(zBankProvisionData),
    urssaf: z.nullable(zBankProvisionData),
    cfe: z.nullable(zBankProvisionData),
    subscriptions: z.nullable(zBankProvisionData),
    buffer: z.nullable(zMoneyData),
    total: zMoneyData
});

/**
 * Ca3BoxesData
 */
export const zCa3BoxesData = z.object({
    salesHt: zMoneyData,
    intraCommunityPurchasesHt: zMoneyData,
    nonEuPurchasesHt: zMoneyData,
    taxableBase: zMoneyData,
    collected: zMoneyData,
    fixedAssets: zMoneyData,
    goodsAndServices: zMoneyData,
    otherDeductible: zMoneyData,
    creditCarried: zMoneyData,
    credit: zMoneyData,
    due: zMoneyData
});

/**
 * ContributionLineData
 */
export const zContributionLineData = z.object({
    kind: zContributionLineKind,
    rateBp: z.int(),
    amount: zMoneyData
});

/**
 * CraData
 */
export const zCraData = z.object({
    id: z.int(),
    missionId: z.int(),
    month: z.string(),
    status: zCraStatus,
    sentOn: z.nullable(z.iso.date()),
    signedOn: z.nullable(z.iso.date()),
    totalDays: z.number(),
    trackedDays: z.number(),
    differenceDays: z.number(),
    estimatedAmount: z.nullable(zMoneyData),
    dirty: z.boolean(),
    editable: z.boolean(),
    notes: z.nullable(z.string()),
    days: z.array(zCraDayData)
});

/**
 * DeadlineInvoiceData
 */
export const zDeadlineInvoiceData = z.object({
    id: z.int(),
    number: z.nullable(z.string()),
    clientName: z.string(),
    missionName: z.nullable(z.string()),
    periodStart: z.nullable(z.iso.date()),
    amount: zMoneyData,
    dueOn: z.iso.date(),
    remindersSent: z.int(),
    lastRemindedOn: z.nullable(z.iso.date())
});

/**
 * DeclarationHistoryUrssafData
 */
export const zDeclarationHistoryUrssafData = z.object({
    period: z.string(),
    total: zMoneyData,
    completion: z.nullable(zDeclarationCompletionData)
});

/**
 * DeclarationHistoryVatData
 */
export const zDeclarationHistoryVatData = z.object({
    due: zMoneyData,
    credit: zMoneyData,
    completion: z.nullable(zDeclarationCompletionData)
});

/**
 * DeclarationHistoryRowData
 */
export const zDeclarationHistoryRowData = z.object({
    period: z.string(),
    urssaf: z.nullable(zDeclarationHistoryUrssafData),
    vat: z.nullable(zDeclarationHistoryVatData)
});

/**
 * ExpenseCategoryTotalData
 */
export const zExpenseCategoryTotalData = z.object({
    category: z.nullable(zExpenseCategory),
    ht: zMoneyData,
    ttc: zMoneyData,
    shareBp: z.int()
});

/**
 * ExpenseMonthPointData
 */
export const zExpenseMonthPointData = z.object({
    month: z.string(),
    ht: zMoneyData,
    ttc: zMoneyData
});

/**
 * ExpenseRegimeProjectionData
 */
export const zExpenseRegimeProjectionData = z.object({
    projectedChargesHt: zMoneyData,
    annualRevenueHt: zMoneyData,
    abatement: zMoneyData,
    microIsFavourable: z.boolean()
});

/**
 * ExpenseTodoData
 */
export const zExpenseTodoData = z.object({
    kind: zExpenseTodoKind,
    expenseId: z.nullable(z.int()),
    subscriptionId: z.nullable(z.int()),
    bankMovementId: z.nullable(z.int()),
    label: z.string(),
    amount: zMoneyData,
    date: z.iso.date()
});

/**
 * ExpensesSubscriptionsData
 */
export const zExpensesSubscriptionsData = z.object({
    monthlyHt: zMoneyData,
    monthlyTtc: zMoneyData,
    yearlyHt: zMoneyData,
    yearlyTtc: zMoneyData,
    count: z.int(),
    annualCount: z.int()
});

/**
 * ExpensesTotalsData
 */
export const zExpensesTotalsData = z.object({
    ht: zMoneyData,
    ttc: zMoneyData,
    count: z.int()
});

/**
 * FiscalDeadlineData
 */
export const zFiscalDeadlineData = z.object({
    kind: zFiscalDeadlineKind,
    periodKey: z.string(),
    periodStart: z.iso.date(),
    periodEnd: z.iso.date(),
    dueOn: z.iso.date(),
    amount: z.nullable(zMoneyData),
    rateBp: z.nullable(z.int()),
    base: z.nullable(zMoneyData),
    isEstimate: z.boolean(),
    completedOn: z.nullable(z.iso.date())
});

/**
 * DeadlineItemData
 */
export const zDeadlineItemData = z.object({
    type: zDeadlineItemType,
    dueOn: z.iso.date(),
    invoice: z.nullable(zDeadlineInvoiceData),
    fiscal: z.nullable(zFiscalDeadlineData)
});

/**
 * DeadlineReminderData
 */
export const zDeadlineReminderData = z.object({
    deadline: zFiscalDeadlineData,
    isRead: z.boolean()
});

/**
 * DeadlineBoardData
 */
export const zDeadlineBoardData = z.object({
    next: z.nullable(zDeadlineItemData),
    items: z.array(zDeadlineItemData),
    reminders: z.array(zDeadlineReminderData),
    calendarToken: z.string(),
    calendarFeed: zCalendarFeedData,
    calendarSubscribedOn: z.nullable(z.iso.date()),
    calendarLastSyncedAt: z.nullable(z.iso.datetime())
});

/**
 * FixedPriceConsumptionData
 */
export const zFixedPriceConsumptionData = z.object({
    referenceDailyRate: zMoneyData,
    trackedDays: z.number(),
    consumed: zMoneyData,
    consumedShareBp: z.int(),
    coveredDays: z.number(),
    remainingDays: z.number(),
    overrun: zMoneyData,
    state: zFixedPriceBudgetState
});

/**
 * IncomeTaxReturnPeriodData
 */
export const zIncomeTaxReturnPeriodData = z.object({
    period: z.string(),
    base: zMoneyData,
    declaredOn: z.nullable(z.iso.date())
});

/**
 * IncomeTaxReturnData
 */
export const zIncomeTaxReturnData = z.object({
    year: z.int(),
    dueOn: z.iso.date(),
    grossReceipts: zMoneyData,
    box: zIncomeTaxReturnBox,
    periods: z.array(zIncomeTaxReturnPeriodData),
    taxableAfterAbatement: zMoneyData,
    liberatingPaymentPaid: z.nullable(zMoneyData),
    completion: z.nullable(zDeclarationCompletionData)
});

/**
 * InvoiceClientTotalsData
 */
export const zInvoiceClientTotalsData = z.object({
    clientId: z.int(),
    all: zMoneyData,
    open: zMoneyData,
    late: zMoneyData,
    paid: zMoneyData,
    draft: zMoneyData
});

/**
 * InvoiceData
 */
export const zInvoiceData = z.object({
    id: z.int(),
    clientId: z.int(),
    missionId: z.nullable(z.int()),
    number: z.nullable(z.string()),
    status: zInvoiceStatus,
    isLate: z.boolean(),
    issuedOn: z.iso.date(),
    dueOn: z.iso.date(),
    paidOn: z.nullable(z.iso.date()),
    periodStart: z.nullable(z.iso.date()),
    periodEnd: z.nullable(z.iso.date()),
    amountHt: zMoneyData,
    amountVat: zMoneyData,
    amountTtc: zMoneyData,
    ttcOverridden: z.boolean(),
    vatRateBp: z.int(),
    notes: z.nullable(z.string())
});

/**
 * InvoiceForecastData
 */
export const zInvoiceForecastData = z.object({
    bucket: zInvoiceForecastBucket,
    amount: zMoneyData,
    shareBp: z.int()
});

/**
 * InvoiceOverdueData
 */
export const zInvoiceOverdueData = z.object({
    amount: zMoneyData,
    count: z.int(),
    maxDaysLate: z.int()
});

/**
 * InvoiceTotalData
 */
export const zInvoiceTotalData = z.object({
    amount: zMoneyData,
    count: z.int()
});

/**
 * MissionData
 */
export const zMissionData = z.object({
    id: z.int(),
    slug: z.string(),
    clientId: z.int(),
    name: z.string(),
    endClientName: z.nullable(z.string()),
    billingMode: zBillingMode,
    rate: z.nullable(zMoneyData),
    referenceDailyRate: z.nullable(zMoneyData),
    rounding: z.nullable(zEntryRounding),
    status: zMissionStatus,
    craRequired: z.boolean(),
    color: z.nullable(zColor),
    notes: z.nullable(z.string()),
    startDate: z.nullable(z.iso.date()),
    endDate: z.nullable(z.iso.date())
});

/**
 * ClientWithMissionsData
 */
export const zClientWithMissionsData = z.object({
    id: z.int(),
    slug: z.string(),
    name: z.string(),
    type: zClientType,
    notes: z.nullable(z.string()),
    siret: z.nullable(z.string()),
    vatNumber: z.nullable(z.string()),
    defaultVatRateBp: z.nullable(z.int()),
    billingAddressLine1: z.nullable(z.string()),
    billingAddressLine2: z.nullable(z.string()),
    billingPostalCode: z.nullable(z.string()),
    billingCity: z.nullable(z.string()),
    billingCountry: z.nullable(z.string()),
    billingContactName: z.nullable(z.string()),
    billingEmail: z.nullable(z.string()),
    color: zColor,
    paymentTermsDays: z.int(),
    archivedAt: z.nullable(z.iso.datetime()),
    createdAt: z.iso.datetime(),
    missions: z.array(zMissionData)
});

/**
 * ClientListData
 */
export const zClientListData = z.object({
    clients: z.array(zClientWithMissionsData)
});

/**
 * CraDetailData
 */
export const zCraDetailData = z.object({
    cra: zCraData,
    client: zClientData,
    mission: zMissionData,
    recipientName: z.string()
});

/**
 * InvoiceDetailData
 */
export const zInvoiceDetailData = z.object({
    invoice: zInvoiceData,
    client: zClientData,
    mission: z.nullable(zMissionData),
    history: z.array(zInvoiceEventData),
    document: z.nullable(zDocumentData)
});

/**
 * InvoiceListItemData
 */
export const zInvoiceListItemData = z.object({
    invoice: zInvoiceData,
    client: zClientData,
    mission: z.nullable(zMissionData)
});

/**
 * InvoiceListData
 */
export const zInvoiceListData = z.object({
    invoices: z.array(zInvoiceListItemData),
    clientTotals: z.array(zInvoiceClientTotalsData),
    nextCursor: z.nullable(z.string())
});

/**
 * MonthWorkloadData
 */
export const zMonthWorkloadData = z.object({
    month: z.string(),
    businessDays: z.int(),
    workedDays: z.int()
});

/**
 * NextInvoiceNumberData
 */
export const zNextInvoiceNumberData = z.object({
    number: z.string(),
    format: z.string()
});

/**
 * PasskeyData
 */
export const zPasskeyData = z.object({
    id: z.int(),
    name: z.string(),
    createdAt: z.string(),
    lastUsedAt: z.nullable(z.string()),
    backedUp: z.boolean()
});

/**
 * PasskeyLoginData
 */
export const zPasskeyLoginData = z.object({
    credential: z.string(),
    remember: z.optional(z.boolean())
});

/**
 * PasskeyOptionsData
 */
export const zPasskeyOptionsData = z.object({
    options: z.record(z.string(), z.unknown())
});

/**
 * PayInvoiceData
 */
export const zPayInvoiceData = z.object({
    paidOn: z.iso.date()
});

/**
 * PersonalTransferData
 */
export const zPersonalTransferData = z.object({
    id: z.int(),
    transferredOn: z.iso.date(),
    amount: zMoneyData,
    note: z.nullable(z.string()),
    reflectedInBalance: z.boolean()
});

/**
 * ReadReceiptData
 */
export const zReadReceiptData = z.object({
    file: z.string()
});

/**
 * RecategorizeExpensesData
 */
export const zRecategorizeExpensesData = z.object({
    expenseIds: z.array(z.int()).check(z.minLength(1)),
    category: zExpenseCategory
});

/**
 * ReceiptFieldConfidence
 *
 * How much a field read off a receipt deserves a second look. High means the value stood next to its own label (« Total TTC », « Date de facture »); Low means it was the best of several candidates.
 *
 */
export const zReceiptFieldConfidence = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * ReceiptAmountFieldData
 */
export const zReceiptAmountFieldData = z.object({
    value: zMoneyData,
    confidence: zReceiptFieldConfidence
});

/**
 * ReceiptDateFieldData
 */
export const zReceiptDateFieldData = z.object({
    value: z.iso.date(),
    confidence: zReceiptFieldConfidence
});

/**
 * ReceiptTextFieldData
 */
export const zReceiptTextFieldData = z.object({
    value: z.string(),
    confidence: zReceiptFieldConfidence
});

/**
 * ReceiptVatFieldData
 */
export const zReceiptVatFieldData = z.object({
    treatment: zExpenseVatTreatment,
    rateBp: z.int(),
    confidence: zReceiptFieldConfidence
});

/**
 * ReceiptSuggestionData
 */
export const zReceiptSuggestionData = z.object({
    textFound: z.boolean(),
    supplier: z.nullish(zReceiptTextFieldData),
    spentOn: z.nullish(zReceiptDateFieldData),
    amountTtc: z.nullish(zReceiptAmountFieldData),
    vat: z.nullish(zReceiptVatFieldData),
    description: z.nullish(zReceiptTextFieldData),
    category: z.nullish(zExpenseCategory)
});

/**
 * RecoveryCodesData
 */
export const zRecoveryCodesData = z.object({
    codes: z.array(z.string())
});

/**
 * RecurringDebitData
 */
export const zRecurringDebitData = z.object({
    label: z.string(),
    amount: zMoneyData,
    debitDay: z.int(),
    months: z.array(z.string()),
    lastBookedOn: z.iso.date()
});

/**
 * RegisterPasskeyData
 */
export const zRegisterPasskeyData = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(100)),
    credential: z.string()
});

/**
 * RegisterUserData
 */
export const zRegisterUserData = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(255)),
    email: z.email().check(z.maxLength(255)),
    password: z.string().check(z.minLength(8)),
    password_confirmation: z.string().check(z.minLength(8))
});

/**
 * RemindInvoiceData
 */
export const zRemindInvoiceData = z.object({
    occurredOn: z.nullish(z.iso.date()),
    note: z.nullish(z.string().check(z.maxLength(2000)))
});

/**
 * RenamePasskeyData
 */
export const zRenamePasskeyData = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(100))
});

/**
 * RevenueBasis
 *
 * The two ways a freelancer reads their revenue: by what was invoiced, or by what actually landed. URSSAF declares on the cash basis; the invoiced basis is the activity view.
 * | |
 * |---|
 * | `0` <br/> Issued invoices, summed on their issue date. |
 * | `1` <br/> Paid invoices, summed on their payment date. |
 */
export const zRevenueBasis = z.union([z.literal(0), z.literal(1)]);

/**
 * RevenueClientData
 */
export const zRevenueClientData = z.object({
    clientId: z.int(),
    clientName: z.string(),
    color: zColor,
    invoiceCount: z.int(),
    total: zMoneyData,
    shareBp: z.int()
});

/**
 * RevenueComparisonData
 */
export const zRevenueComparisonData = z.object({
    period: z.string(),
    total: zMoneyData,
    changeBp: z.nullable(z.int())
});

/**
 * RevenueMonthData
 */
export const zRevenueMonthData = z.object({
    month: z.string(),
    total: zMoneyData,
    inPeriod: z.boolean(),
    shareBp: z.int()
});

/**
 * RevenueNetData
 */
export const zRevenueNetData = z.object({
    amount: zMoneyData,
    contributions: zMoneyData,
    rateBp: z.int()
});

/**
 * RevenueVatData
 */
export const zRevenueVatData = z.object({
    amount: zMoneyData,
    rateBp: z.nullable(z.int())
});

/**
 * RevenueData
 */
export const zRevenueData = z.object({
    period: z.string(),
    basis: zRevenueBasis,
    fellBack: z.boolean(),
    lastActivePeriod: z.nullable(z.string()),
    total: zMoneyData,
    previous: zRevenueComparisonData,
    vat: z.nullable(zRevenueVatData),
    net: z.nullable(zRevenueNetData),
    months: z.array(zRevenueMonthData),
    invoices: z.array(zInvoiceListItemData),
    clients: z.array(zRevenueClientData)
});

/**
 * SendCraData
 */
export const zSendCraData = z.object({
    applySignature: z.optional(z.boolean()),
    sentOn: z.nullish(z.iso.date())
});

/**
 * SendInvoiceData
 */
export const zSendInvoiceData = z.object({
    sentOn: z.nullish(z.iso.date())
});

/**
 * SentryWebData
 */
export const zSentryWebData = z.object({
    dsn: z.string(),
    environment: z.string(),
    tracesSampleRate: z.number()
});

/**
 * PingData
 */
export const zPingData = z.object({
    status: z.string(),
    version: z.string(),
    sentry: z.nullable(zSentryWebData)
});

/**
 * SignedMoneyData
 */
export const zSignedMoneyData = z.object({
    amount: z.int(),
    currency: zCurrency
});

/**
 * BankBalanceData
 */
export const zBankBalanceData = z.object({
    amount: zSignedMoneyData,
    source: zBankBalanceSource,
    asOf: z.nullable(z.iso.date())
});

/**
 * BankMovementData
 */
export const zBankMovementData = z.object({
    id: z.int(),
    bookedOn: z.iso.date(),
    label: z.string(),
    amount: zSignedMoneyData,
    runningBalance: z.nullable(zSignedMoneyData),
    invoice: z.nullable(zBankMovementInvoiceData),
    pendingMatchId: z.nullable(z.int()),
    expense: z.nullable(zBankMovementExpenseData)
});

/**
 * BankAccountData
 */
export const zBankAccountData = z.object({
    balance: z.nullable(zBankBalanceData),
    provisions: zBankProvisionsData,
    pendingMatches: z.array(zBankMatchData),
    movements: z.array(zBankMovementData),
    nextMovementsCursor: z.nullable(z.string()),
    hasUnlinkedCredits: z.boolean(),
    statements: z.array(zBankStatementData)
});

/**
 * BankImportData
 */
export const zBankImportData = z.object({
    lineCount: z.int(),
    importedCount: z.int(),
    suggestionCount: z.int(),
    account: zBankAccountData
});

/**
 * BankMovementPageData
 */
export const zBankMovementPageData = z.object({
    movements: z.array(zBankMovementData),
    nextCursor: z.nullable(z.string())
});

/**
 * CfeReturnData
 */
export const zCfeReturnData = z.object({
    year: z.int(),
    dueOn: z.iso.date(),
    expected: z.nullable(zMoneyData),
    isEstimate: z.boolean(),
    provisioned: z.nullable(zMoneyData),
    gap: z.nullable(zSignedMoneyData),
    monthsProvisioned: z.int(),
    completion: z.nullable(zDeclarationCompletionData)
});

/**
 * AnnualDeclarationsData
 */
export const zAnnualDeclarationsData = z.object({
    incomeTaxReturn: zIncomeTaxReturnData,
    cfe: z.nullable(zCfeReturnData)
});

/**
 * DeclarationSettlementData
 */
export const zDeclarationSettlementData = z.object({
    expected: zMoneyData,
    provisioned: z.nullable(zMoneyData),
    gap: z.nullable(zSignedMoneyData),
    detectedPayments: zMoneyData
});

/**
 * ExpensesVatSummaryData
 */
export const zExpensesVatSummaryData = z.object({
    deductible: zMoneyData,
    blocked: zMoneyData,
    blockedCount: z.int(),
    reverseCharged: zMoneyData,
    deferred: zMoneyData,
    collected: zMoneyData,
    balance: zSignedMoneyData
});

/**
 * FixedPriceBudgetData
 */
export const zFixedPriceBudgetData = z.object({
    forfait: zMoneyData,
    invoiced: zMoneyData,
    draft: zMoneyData,
    remaining: zSignedMoneyData,
    invoicedShareBp: z.int(),
    consumption: z.nullable(zFixedPriceConsumptionData)
});

/**
 * InvoiceTodoBudgetData
 */
export const zInvoiceTodoBudgetData = z.object({
    missionId: z.int(),
    missionName: z.string(),
    missionSlug: z.string(),
    clientSlug: z.string(),
    budget: zFixedPriceBudgetData,
    vatRateBp: z.int()
});

/**
 * InvoiceTodoData
 */
export const zInvoiceTodoData = z.object({
    kind: zInvoiceTodoKind,
    amount: zMoneyData,
    clientId: z.int(),
    clientName: z.string(),
    overdue: z.nullish(zInvoiceTodoOverdueData),
    work: z.nullish(zInvoiceTodoWorkData),
    budget: z.nullish(zInvoiceTodoBudgetData)
});

/**
 * InvoiceSummaryData
 */
export const zInvoiceSummaryData = z.object({
    month: z.string(),
    toCollect: zInvoiceTotalData,
    overdue: zInvoiceOverdueData,
    forecast: z.array(zInvoiceForecastData),
    monthUnbilled: zInvoiceTotalData,
    unbilled: zInvoiceTotalData,
    counts: zInvoiceCountsData,
    todo: z.array(zInvoiceTodoData),
    todoTotal: z.int()
});

/**
 * MissionRevenueData
 */
export const zMissionRevenueData = z.object({
    missionId: z.int(),
    yearToDate: zMoneyData,
    currentMonth: zMoneyData,
    total: zMoneyData,
    monthlyAverage: z.nullable(zMoneyData),
    currentMonthDays: z.nullable(z.number()),
    currentMonthMinutes: z.nullable(z.int()),
    fixedPrice: z.nullish(zFixedPriceBudgetData)
});

/**
 * ClientRevenueData
 */
export const zClientRevenueData = z.object({
    clientId: z.int(),
    yearToDate: zMoneyData,
    pending: zMoneyData,
    averagePaymentDelayDays: z.nullable(z.int()),
    missions: z.array(zMissionRevenueData)
});

/**
 * ClientRevenueDetailData
 */
export const zClientRevenueDetailData = z.object({
    year: z.int(),
    revenue: zClientRevenueData
});

/**
 * ClientRevenueListData
 */
export const zClientRevenueListData = z.object({
    year: z.int(),
    clients: z.array(zClientRevenueData)
});

/**
 * RevenueCeilingData
 */
export const zRevenueCeilingData = z.object({
    year: z.int(),
    collectedHt: zMoneyData,
    ceiling: zMoneyData,
    shareBp: z.int(),
    margin: zSignedMoneyData
});

/**
 * StartTimerData
 */
export const zStartTimerData = z.object({
    missionId: z.int()
});

/**
 * StopTimerData
 */
export const zStopTimerData = z.object({
    date: z.iso.date(),
    durationMinutes: z.int().check(z.gte(1), z.lte(1440)),
    rounding: z.nullish(zEntryRounding),
    note: z.nullable(z.string().check(z.maxLength(2000))),
    billable: z.optional(z.boolean())
});

/**
 * SubscriptionAmountChangeData
 */
export const zSubscriptionAmountChangeData = z.object({
    subscriptionId: z.int(),
    supplier: z.string(),
    before: zMoneyData,
    after: zMoneyData,
    changeBp: z.int(),
    since: z.iso.date()
});

/**
 * SubscriptionAmountData
 */
export const zSubscriptionAmountData = z.object({
    effectiveFrom: z.iso.date(),
    amountHt: zMoneyData
});

/**
 * SubscriptionCategoryTotalData
 */
export const zSubscriptionCategoryTotalData = z.object({
    category: zExpenseCategory,
    yearlyHt: zMoneyData
});

/**
 * SubscriptionKpisData
 */
export const zSubscriptionKpisData = z.object({
    monthlyTtc: zMoneyData,
    monthlyCount: z.int(),
    yearlyTtc: zMoneyData,
    annualCount: z.int(),
    provisionedCount: z.int(),
    provisionedPerMonth: zMoneyData,
    recoverableVatPerYear: zMoneyData,
    reverseChargedVatPerYear: zMoneyData,
    missingReceipts: z.int()
});

/**
 * SubscriptionOccurrenceState
 *
 * One square of the twelve-month strip.
 * | |
 * |---|
 * | `0` <br/> The debit has its expense and the expense its receipt. |
 * | `1` <br/> The debit has its expense, still waiting for the receipt. |
 * | `2` <br/>  |
 * | `3` <br/> A future debit that will not happen while the subscription is paused. |
 * | `4` <br/> A past debit with no expense — before the subscription was recorded, or not auto-created. |
 */
export const zSubscriptionOccurrenceState = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4)
]);

/**
 * SubscriptionOccurrenceData
 */
export const zSubscriptionOccurrenceData = z.object({
    period: z.string(),
    debitOn: z.iso.date(),
    state: zSubscriptionOccurrenceState,
    expenseId: z.nullable(z.int())
});

/**
 * SubscriptionPeriodicity
 */
export const zSubscriptionPeriodicity = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * ExpenseSubscriptionData
 */
export const zExpenseSubscriptionData = z.object({
    id: z.int(),
    supplier: z.string(),
    periodicity: zSubscriptionPeriodicity
});

/**
 * ExpenseData
 */
export const zExpenseData = z.object({
    id: z.int(),
    supplier: z.string(),
    spentOn: z.iso.date(),
    category: zExpenseCategory,
    description: z.nullable(z.string()),
    amountHt: zMoneyData,
    vat: zMoneyData,
    amountTtc: zMoneyData,
    recoverableVat: zMoneyData,
    vatTreatment: zExpenseVatTreatment,
    vatRateBp: z.int(),
    proShareBp: z.int(),
    receipt: z.nullable(zExpenseReceiptData),
    subscription: z.nullable(zExpenseSubscriptionData),
    bankMovement: z.nullable(zExpenseBankMovementData),
    vatStatus: zExpenseVatStatus,
    vatClaimPeriod: z.string(),
    isRegularisation: z.boolean()
});

/**
 * ExpensesMonthData
 */
export const zExpensesMonthData = z.object({
    month: z.string(),
    declaredOn: z.nullable(z.iso.date()),
    vat: z.nullable(zExpensesVatSummaryData),
    totals: zExpensesTotalsData,
    subscriptions: z.nullable(zExpensesSubscriptionsData),
    categories: z.array(zExpenseCategoryTotalData),
    series: z.array(zExpenseMonthPointData),
    projection: z.nullable(zExpenseRegimeProjectionData),
    todo: z.array(zExpenseTodoData),
    expenses: z.array(zExpenseData)
});

/**
 * SubscriptionData
 */
export const zSubscriptionData = z.object({
    id: z.int(),
    supplier: z.string(),
    category: zExpenseCategory,
    description: z.nullable(z.string()),
    amountHt: zMoneyData,
    vat: zMoneyData,
    amountTtc: zMoneyData,
    recoverableVat: zMoneyData,
    proShareBp: z.int(),
    vatTreatment: zExpenseVatTreatment,
    vatRateBp: z.int(),
    periodicity: zSubscriptionPeriodicity,
    debitDay: z.int(),
    debitMonth: z.nullable(z.int()),
    startedOn: z.iso.date(),
    customerSpaceUrl: z.nullable(z.string()),
    autoCreateExpenses: z.boolean(),
    provisionMonthly: z.boolean(),
    monthlyProvision: z.nullable(zMoneyData),
    isPaused: z.boolean(),
    cancelledOn: z.nullable(z.iso.date()),
    nextDebitOn: z.nullable(z.iso.date()),
    amounts: z.array(zSubscriptionAmountData),
    occurrences: z.array(zSubscriptionOccurrenceData)
});

/**
 * SubscriptionInputData
 */
export const zSubscriptionInputData = z.object({
    supplier: z.string().check(z.minLength(1), z.maxLength(120)),
    category: zExpenseCategory,
    amountHt: z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    }),
    vatTreatment: zExpenseVatTreatment,
    vatRateBp: z.int().check(z.gte(0), z.lte(10000)),
    periodicity: zSubscriptionPeriodicity,
    debitDay: z.int().check(z.gte(1), z.lte(31)),
    startedOn: z.iso.date(),
    proShareBp: z.optional(z.int().check(z.gte(0), z.lte(10000))),
    debitMonth: z.nullish(z.int().check(z.gte(1), z.lte(12))),
    description: z.nullish(z.string().check(z.maxLength(255))),
    customerSpaceUrl: z.nullish(z.url().check(z.maxLength(2048))),
    autoCreateExpenses: z.optional(z.boolean()),
    provisionMonthly: z.optional(z.boolean())
});

/**
 * SummarizeDeclarationsData
 */
export const zSummarizeDeclarationsData = z.object({
    period: z.nullish(z.string().check(z.regex(/^(19|20)\d{2}-(0[1-9]|1[0-2])$/)))
});

/**
 * Theme
 */
export const zTheme = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * TimeEntryData
 */
export const zTimeEntryData = z.object({
    id: z.int(),
    missionId: z.int(),
    date: z.iso.date(),
    durationMinutes: z.int(),
    rounding: z.nullable(zEntryRounding),
    valuedMinutes: z.nullable(z.int()),
    valuedDayFraction: z.nullable(z.number()),
    value: z.nullable(zMoneyData),
    billable: z.boolean(),
    invoiced: z.boolean(),
    note: z.nullable(z.string())
});

/**
 * TimeEntryInputData
 */
export const zTimeEntryInputData = z.object({
    missionId: z.int(),
    date: z.iso.date(),
    durationMinutes: z.int().check(z.gte(1), z.lte(1440)),
    rounding: z.nullish(zEntryRounding),
    billable: z.optional(z.boolean()),
    note: z.nullish(z.string().check(z.maxLength(2000)))
});

/**
 * TimeEntryListData
 */
export const zTimeEntryListData = z.object({
    timeEntries: z.array(zTimeEntryData)
});

/**
 * TimerState
 */
export const zTimerState = z.union([z.literal(0), z.literal(1)]);

/**
 * TimerData
 */
export const zTimerData = z.object({
    id: z.int(),
    missionId: z.int(),
    missionName: z.string(),
    missionColor: zColor,
    state: zTimerState,
    startedAt: z.iso.datetime(),
    elapsedSeconds: z.int(),
    note: z.nullable(z.string())
});

/**
 * TimerStateData
 */
export const zTimerStateData = z.object({
    timer: z.nullable(zTimerData),
    lastMissionId: z.nullable(z.int())
});

/**
 * TotpSetupData
 */
export const zTotpSetupData = z.object({
    secret: z.string(),
    otpauthUri: z.string()
});

/**
 * TreasuryData
 */
export const zTreasuryData = z.object({
    balance: z.nullable(zBankBalanceData),
    pendingTransfers: zMoneyData,
    coveredThrough: z.nullable(z.iso.date()),
    provisions: zBankProvisionsData,
    transferable: z.nullable(zSignedMoneyData),
    transfers: z.array(zPersonalTransferData)
});

/**
 * TrimTimerData
 */
export const zTrimTimerData = z.object({
    seconds: z.int().check(z.gte(1), z.lte(86400))
});

/**
 * TrustedDeviceData
 */
export const zTrustedDeviceData = z.object({
    id: z.int(),
    browser: z.nullable(z.string()),
    platform: z.nullable(z.string()),
    lastUsedAt: z.nullable(z.string()),
    expiresAt: z.string(),
    current: z.boolean()
});

/**
 * TwoFactorChallengeAnswerData
 */
export const zTwoFactorChallengeAnswerData = z.object({
    code: z.nullish(z.string()),
    recoveryCode: z.nullish(z.string().check(z.regex(/^[A-Za-z0-9]{10}-[A-Za-z0-9]{10}$/))),
    passkey: z.nullish(z.string()),
    trustDevice: z.optional(z.boolean())
});

/**
 * TwoFactorMethod
 */
export const zTwoFactorMethod = z.union([z.literal(0), z.literal(1)]);

/**
 * TwoFactorChallengeData
 */
export const zTwoFactorChallengeData = z.object({
    methods: z.array(zTwoFactorMethod),
    twoFactorRequired: z.optional(z.boolean())
});

/**
 * TwoFactorStatusData
 */
export const zTwoFactorStatusData = z.object({
    totpEnabled: z.boolean(),
    totpConfirmedAt: z.nullable(z.string()),
    recoveryCodesRemaining: z.int(),
    passkeys: z.array(zPasskeyData),
    trustedDevices: z.array(zTrustedDeviceData)
});

/**
 * UpcomingDebitData
 */
export const zUpcomingDebitData = z.object({
    subscriptionId: z.int(),
    supplier: z.string(),
    dueOn: z.iso.date(),
    amountTtc: zMoneyData,
    periodicity: zSubscriptionPeriodicity,
    isProvision: z.boolean()
});

/**
 * SubscriptionsData
 */
export const zSubscriptionsData = z.object({
    kpis: zSubscriptionKpisData,
    subscriptions: z.array(zSubscriptionData),
    upcoming: z.array(zUpcomingDebitData),
    categories: z.array(zSubscriptionCategoryTotalData),
    yearlyHt: zMoneyData,
    amountChanges: z.array(zSubscriptionAmountChangeData),
    detected: z.array(zRecurringDebitData)
});

/**
 * UpdateBankBalanceData
 */
export const zUpdateBankBalanceData = z.object({
    balance: z.nullish(z.object({
        amount: z.int().check(z.gte(-100000000000), z.lte(100000000000)),
        currency: zCurrency
    }))
});

/**
 * UpdateCalendarFeedData
 */
export const zUpdateCalendarFeedData = z.object({
    invoices: z.boolean(),
    reminders: z.boolean(),
    vat: z.boolean(),
    urssaf: z.boolean(),
    other: z.boolean()
});

/**
 * UpdateClientData
 */
export const zUpdateClientData = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(255)),
    type: zClientType,
    notes: z.nullish(z.string().check(z.maxLength(2000))),
    siret: z.nullish(z.string().check(z.maxLength(255))),
    vatNumber: z.nullish(z.string().check(z.maxLength(255))),
    defaultVatRateBp: z.nullish(z.int().check(z.gte(0), z.lte(10000))),
    billingAddressLine1: z.nullish(z.string().check(z.maxLength(255))),
    billingAddressLine2: z.nullish(z.string().check(z.maxLength(255))),
    billingPostalCode: z.nullish(z.string().check(z.maxLength(32))),
    billingCity: z.nullish(z.string().check(z.maxLength(255))),
    billingCountry: z.nullish(z.string().check(z.maxLength(255))),
    billingContactName: z.nullish(z.string().check(z.maxLength(255))),
    billingEmail: z.nullish(z.email().check(z.maxLength(255))),
    color: z.optional(zColor),
    paymentTermsDays: z.optional(z.int().check(z.gte(0), z.lte(365)))
});

/**
 * UpdateCraDaysData
 */
export const zUpdateCraDaysData = z.object({
    days: z.array(z.object({
        date: z.iso.date(),
        dayFractionBp: z.int().check(z.gte(1), z.lte(10000))
    }))
});

/**
 * UpdateDocumentData
 */
export const zUpdateDocumentData = z.object({
    category: zDocumentCategory
});

/**
 * UpdateInvoiceData
 */
export const zUpdateInvoiceData = z.object({
    clientId: z.int(),
    amountHt: z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    }),
    missionId: z.nullish(z.int()),
    number: z.nullish(z.string().check(z.minLength(1), z.maxLength(255))),
    issuedOn: z.nullish(z.iso.date()),
    dueOn: z.nullish(z.iso.date()),
    paidOn: z.nullish(z.iso.date()),
    periodStart: z.nullish(z.iso.date()),
    periodEnd: z.nullish(z.iso.date()),
    amountTtc: z.nullish(z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    })),
    vatRateBp: z.nullish(z.int().check(z.gte(0), z.lte(10000))),
    notes: z.nullish(z.string().check(z.maxLength(2000)))
});

/**
 * UpdateMissionData
 */
export const zUpdateMissionData = z.object({
    name: z.string().check(z.minLength(1), z.maxLength(255)),
    billingMode: zBillingMode,
    status: zMissionStatus,
    rate: z.nullish(z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    })),
    referenceDailyRate: z.nullish(z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    })),
    endClientName: z.nullish(z.string().check(z.minLength(1), z.maxLength(255))),
    rounding: z.nullish(zEntryRounding),
    craRequired: z.nullish(z.boolean()),
    color: z.nullish(zColor),
    notes: z.nullish(z.string().check(z.maxLength(2000))),
    startDate: z.nullish(z.iso.date()),
    endDate: z.nullish(z.iso.date())
});

/**
 * UpdateReleaseNotesSeenData
 */
export const zUpdateReleaseNotesSeenData = z.object({
    version: z.string().check(z.maxLength(32), z.regex(/^\d+\.\d+\.\d+$/))
});

/**
 * UpdateSettingsCurrencyData
 */
export const zUpdateSettingsCurrencyData = z.object({
    currency: zCurrency
});

/**
 * UpdateTimerData
 */
export const zUpdateTimerData = z.object({
    note: z.nullable(z.string().check(z.maxLength(2000)))
});

/**
 * UpdateUserThemeData
 */
export const zUpdateUserThemeData = z.object({
    theme: zTheme
});

/**
 * UploadClientLogoData
 */
export const zUploadClientLogoData = z.object({
    logo: z.string()
});

/**
 * UploadDocumentData
 */
export const zUploadDocumentData = z.object({
    file: z.string(),
    category: z.nullish(zDocumentCategory),
    fileName: z.nullish(z.string().check(z.maxLength(255)))
});

/**
 * UploadExpenseReceiptData
 */
export const zUploadExpenseReceiptData = z.object({
    file: z.string()
});

/**
 * UploadInvoiceDocumentData
 */
export const zUploadInvoiceDocumentData = z.object({
    file: z.string()
});

/**
 * UploadSignatureData
 */
export const zUploadSignatureData = z.object({
    signature: z.string()
});

/**
 * UploadSignedCraData
 */
export const zUploadSignedCraData = z.object({
    file: z.string(),
    signedOn: z.nullish(z.iso.date())
});

/**
 * UrssafPeriodicity
 */
export const zUrssafPeriodicity = z.union([z.literal(0), z.literal(1)]);

/**
 * UrssafDeclarationData
 */
export const zUrssafDeclarationData = z.object({
    period: z.string(),
    periodicity: zUrssafPeriodicity,
    coversShownMonth: z.boolean(),
    base: zMoneyData,
    invoiceCount: z.int(),
    lines: z.array(zContributionLineData),
    total: zMoneyData,
    deadline: z.nullable(zDeclarationDeadlineData),
    completion: z.nullable(zDeclarationCompletionData),
    settlement: zDeclarationSettlementData
});

/**
 * UserData
 */
export const zUserData = z.object({
    id: z.int(),
    name: z.string(),
    email: z.string(),
    theme: zTheme,
    releaseNotesSeenVersion: z.nullable(z.string()),
    locale: zLocale,
    dateFormat: zDateFormat,
    currency: zCurrency,
    businessCountry: z.string(),
    hasFrenchFiscality: z.boolean(),
    vatLiable: z.boolean(),
    effectiveVatRateBp: z.int(),
    timezone: z.string(),
    workdayMinutes: z.int(),
    defaultPaymentTermsDays: z.int(),
    effectiveContributionRateBp: z.int()
});

/**
 * VatRegime
 */
export const zVatRegime = z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2)
]);

/**
 * SettingsData
 */
export const zSettingsData = z.object({
    tradeName: z.nullable(z.string()),
    siret: z.nullable(z.string()),
    vatNumber: z.nullable(z.string()),
    signatureCity: z.nullable(z.string()),
    contactEmail: z.nullable(z.string()),
    phone: z.nullable(z.string()),
    companyAddressLine1: z.nullable(z.string()),
    companyAddressLine2: z.nullable(z.string()),
    companyPostalCode: z.nullable(z.string()),
    companyCity: z.nullable(z.string()),
    homeAddressSameAsCompany: z.boolean(),
    homeAddressLine1: z.nullable(z.string()),
    homeAddressLine2: z.nullable(z.string()),
    homePostalCode: z.nullable(z.string()),
    homeCity: z.nullable(z.string()),
    businessCountry: z.string(),
    hasFrenchFiscality: z.boolean(),
    urssafPeriodicity: zUrssafPeriodicity,
    autoRates: z.boolean(),
    businessStartedOn: z.nullable(z.iso.date()),
    acre: z.boolean(),
    ratesCheckedAt: z.nullable(z.string()),
    ratesYear: z.nullable(z.int()),
    ratesRefreshing: z.boolean(),
    contributionRateBp: z.int(),
    liberatingPayment: z.boolean(),
    liberatingPaymentRateBp: z.int(),
    vatRegime: zVatRegime,
    vatLiable: z.boolean(),
    defaultVatRateBp: z.int(),
    effectiveVatRateBp: z.int(),
    effectiveContributionRateBp: z.int(),
    defaultPaymentTermsDays: z.int(),
    invoiceNumberFormat: z.string(),
    treasuryBuffer: z.nullable(zMoneyData),
    cfeExpected: z.nullable(zMoneyData),
    currency: zCurrency,
    currencyLocked: z.boolean(),
    locale: zLocale,
    dateFormat: zDateFormat,
    timezone: z.string(),
    workdayMinutes: z.int(),
    dormantAfterMonths: z.nullable(z.int()),
    hasSignature: z.boolean()
});

/**
 * UpdateSettingsData
 */
export const zUpdateSettingsData = z.object({
    businessCountry: z.string().check(z.regex(/^[A-Z]{2}$/)),
    locale: zLocale,
    dateFormat: zDateFormat,
    timezone: z.string(),
    workdayMinutes: z.int().check(z.gte(60), z.lte(1440)),
    urssafPeriodicity: zUrssafPeriodicity,
    autoRates: z.boolean(),
    acre: z.boolean(),
    contributionRateBp: z.int().check(z.gte(0), z.lte(10000)),
    liberatingPayment: z.boolean(),
    liberatingPaymentRateBp: z.int().check(z.gte(0), z.lte(10000)),
    vatRegime: zVatRegime,
    defaultVatRateBp: z.int().check(z.gte(0), z.lte(10000)),
    defaultPaymentTermsDays: z.int().check(z.gte(0), z.lte(365)),
    invoiceNumberFormat: z.string().check(z.maxLength(64)),
    homeAddressSameAsCompany: z.boolean(),
    tradeName: z.nullish(z.string().check(z.maxLength(255))),
    siret: z.nullish(z.string().check(z.maxLength(255))),
    vatNumber: z.nullish(z.string().check(z.maxLength(255))),
    signatureCity: z.nullish(z.string().check(z.maxLength(255))),
    contactEmail: z.nullish(z.email().check(z.maxLength(255))),
    phone: z.nullish(z.string().check(z.maxLength(64))),
    dormantAfterMonths: z.nullish(z.int().check(z.gte(1), z.lte(60))),
    companyAddressLine1: z.nullish(z.string().check(z.maxLength(255))),
    companyAddressLine2: z.nullish(z.string().check(z.maxLength(255))),
    companyPostalCode: z.nullish(z.string().check(z.maxLength(32))),
    companyCity: z.nullish(z.string().check(z.maxLength(255))),
    homeAddressLine1: z.nullish(z.string().check(z.maxLength(255))),
    homeAddressLine2: z.nullish(z.string().check(z.maxLength(255))),
    homePostalCode: z.nullish(z.string().check(z.maxLength(32))),
    homeCity: z.nullish(z.string().check(z.maxLength(255))),
    businessStartedOn: z.nullish(z.iso.date()),
    treasuryBuffer: z.nullish(z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    })),
    cfeExpected: z.nullish(z.object({
        amount: z.int().check(z.gte(1), z.lte(100000000000)),
        currency: zCurrency
    }))
});

/**
 * VatDeclarationData
 */
export const zVatDeclarationData = z.object({
    period: z.string(),
    regime: zVatRegime,
    salesHt: zMoneyData,
    collected: zMoneyData,
    rateBp: z.nullable(z.int()),
    boxes: zCa3BoxesData,
    invoiceCount: z.int(),
    expenseCount: z.int(),
    reverseChargedVat: zMoneyData,
    creditIsRefundable: z.boolean(),
    deadline: z.nullable(zDeclarationDeadlineData),
    completion: z.nullable(zDeclarationCompletionData),
    settlement: zDeclarationSettlementData
});

/**
 * DeclarationsData
 */
export const zDeclarationsData = z.object({
    period: z.string(),
    previousPeriod: z.string(),
    nextPeriod: z.nullable(z.string()),
    isDefault: z.boolean(),
    urssaf: z.nullable(zUrssafDeclarationData),
    vat: z.nullable(zVatDeclarationData),
    cumulative: z.nullable(zRevenueCeilingData),
    annual: z.nullable(zAnnualDeclarationsData),
    history: z.array(zDeclarationHistoryRowData)
});

export const zGetPingResponse = zPingData;

export const zRegisterBody = zRegisterUserData;

export const zRegisterResponse = zUserData;

export const zLoginBody = zLoginData;

export const zLoginResponse = z.union([
    zUserData,
    zTwoFactorChallengeData
]);

/**
 * No content
 */
export const zLogoutResponse = z.void();

export const zCurrentUserResponse = zUserData;

export const zConfirmPasswordBody = zConfirmPasswordData;

/**
 * No content
 */
export const zConfirmPasswordResponse = z.void();

export const zUpdateUserThemeBody = zUpdateUserThemeData;

export const zUpdateUserThemeResponse = zUserData;

export const zUpdateUserReleaseNotesSeenBody = zUpdateReleaseNotesSeenData;

export const zUpdateUserReleaseNotesSeenResponse = zUserData;

export const zShowBankAccountResponse = zBankAccountData;

export const zListBankMovementsQuery = z.object({
    cursor: z.nullish(z.string().check(z.maxLength(1024)))
});

export const zListBankMovementsResponse = zBankMovementPageData;

export const zUpdateBankBalanceBody = zUpdateBankBalanceData;

export const zUpdateBankBalanceResponse = zBankAccountData;

export const zImportBankStatementBody = zImportBankStatementData;

export const zImportBankStatementResponse = zBankImportData;

export const zValidateBankMatchPath = z.object({
    match: z.int()
});

export const zValidateBankMatchResponse = zBankAccountData;

export const zDismissBankMatchPath = z.object({
    match: z.int()
});

export const zDismissBankMatchResponse = zBankAccountData;

export const zListClientsResponse = zClientListData;

export const zCreateClientBody = zCreateClientData;

export const zCreateClientResponse = zClientData;

export const zDeleteClientPath = z.object({
    client: z.string()
});

/**
 * No content
 */
export const zDeleteClientResponse = z.void();

export const zShowClientPath = z.object({
    client: z.string()
});

export const zShowClientResponse = zClientWithMissionsData;

export const zUpdateClientBody = zUpdateClientData;

export const zUpdateClientPath = z.object({
    client: z.string()
});

export const zUpdateClientResponse = zClientData;

export const zArchiveClientPath = z.object({
    client: z.string()
});

export const zArchiveClientResponse = zClientData;

export const zUnarchiveClientPath = z.object({
    client: z.string()
});

export const zUnarchiveClientResponse = zClientData;

export const zListClientDocumentsPath = z.object({
    client: z.string()
});

export const zListClientDocumentsResponse = zDocumentListData;

export const zUploadClientDocumentBody = zUploadDocumentData;

export const zUploadClientDocumentPath = z.object({
    client: z.string()
});

export const zUploadClientDocumentResponse = zDocumentData;

export const zDeleteClientDocumentPath = z.object({
    client: z.string(),
    document: z.int()
});

/**
 * No content
 */
export const zDeleteClientDocumentResponse = z.void();

export const zUpdateClientDocumentBody = zUpdateDocumentData;

export const zUpdateClientDocumentPath = z.object({
    client: z.string(),
    document: z.int()
});

export const zUpdateClientDocumentResponse = zDocumentData;

export const zDownloadClientDocumentPath = z.object({
    client: z.string(),
    document: z.int()
});

export const zDownloadClientDocumentResponse = z.string();

export const zDeleteClientLogoPath = z.object({
    client: z.string()
});

/**
 * No content
 */
export const zDeleteClientLogoResponse = z.void();

export const zShowClientLogoPath = z.object({
    client: z.string()
});

export const zShowClientLogoResponse = z.string();

export const zUploadClientLogoBody = zUploadClientLogoData;

export const zUploadClientLogoPath = z.object({
    client: z.string()
});

/**
 * No content
 */
export const zUploadClientLogoResponse = z.void();

export const zShowClientRevenuePath = z.object({
    client: z.string()
});

export const zShowClientRevenueResponse = zClientRevenueDetailData;

export const zShowMissionRevenuePath = z.object({
    client: z.string(),
    mission: z.string()
});

export const zShowMissionRevenueResponse = zMissionRevenueData;

export const zListClientRevenueResponse = zClientRevenueListData;

export const zListCrasQuery = z.object({
    month: z.nullish(z.string().check(z.regex(/^(19|20)\d{2}-(0[1-9]|1[0-2])$/)))
});

export const zListCrasResponse = zCraListData;

export const zCreateCraBody = zCreateCraData;

export const zCreateCraResponse = zCraDetailData;

export const zDeleteCraPath = z.object({
    cra: z.int()
});

/**
 * No content
 */
export const zDeleteCraResponse = z.void();

export const zShowCraPath = z.object({
    cra: z.int()
});

export const zShowCraResponse = zCraDetailData;

export const zUpdateCraDaysBody = zUpdateCraDaysData;

export const zUpdateCraDaysPath = z.object({
    cra: z.int()
});

export const zUpdateCraDaysResponse = zCraDetailData;

export const zResetCraPath = z.object({
    cra: z.int()
});

export const zResetCraResponse = zCraDetailData;

export const zSendCraBody = zSendCraData;

export const zSendCraPath = z.object({
    cra: z.int()
});

export const zSendCraResponse = zCraDetailData;

export const zReopenCraPath = z.object({
    cra: z.int()
});

export const zReopenCraResponse = zCraDetailData;

export const zUploadSignedCraBody = zUploadSignedCraData;

export const zUploadSignedCraPath = z.object({
    cra: z.int()
});

export const zUploadSignedCraResponse = zCraDetailData;

export const zDownloadCraPdfPath = z.object({
    cra: z.int()
});

export const zDownloadCraPdfQuery = z.object({
    applySignature: z.optional(z.boolean())
});

export const zDownloadCraPdfResponse = z.string();

export const zListDeadlinesResponse = zDeadlineBoardData;

export const zCompleteDeadlineBody = zCompleteFiscalDeadlineData;

export const zCompleteDeadlineResponse = zDeadlineBoardData;

export const zUncompleteDeadlinePath = z.object({
    kind: z.int(),
    periodKey: z.string()
});

export const zUncompleteDeadlineResponse = zDeadlineBoardData;

export const zMarkDeadlineRemindersReadResponse = zDeadlineBoardData;

export const zUpdateCalendarFeedBody = zUpdateCalendarFeedData;

export const zUpdateCalendarFeedResponse = zDeadlineBoardData;

export const zRegenerateCalendarTokenResponse = zDeadlineBoardData;

export const zInterruptCalendarSubscriptionResponse = zDeadlineBoardData;

export const zConfirmCalendarSubscriptionResponse = zDeadlineBoardData;

export const zShowDeadlineCalendarPath = z.object({
    token: z.string()
});

export const zShowDeadlineCalendarResponse = z.string();

export const zShowDeclarationsQuery = z.object({
    period: z.nullish(z.string().check(z.regex(/^(19|20)\d{2}-(0[1-9]|1[0-2])$/)))
});

export const zShowDeclarationsResponse = zDeclarationsData;

export const zMarkDeclarationFiledBody = zCompleteDeclarationData;

export const zMarkDeclarationFiledResponse = zDeclarationsData;

export const zUnmarkDeclarationFiledPath = z.object({
    kind: z.int(),
    periodKey: z.string()
});

export const zUnmarkDeclarationFiledQuery = z.object({
    period: z.nullish(z.string().check(z.regex(/^(19|20)\d{2}-(0[1-9]|1[0-2])$/)))
});

export const zUnmarkDeclarationFiledResponse = zDeclarationsData;

export const zClearDeclarationPaymentPath = z.object({
    kind: z.int(),
    periodKey: z.string()
});

export const zClearDeclarationPaymentQuery = z.object({
    period: z.nullish(z.string().check(z.regex(/^(19|20)\d{2}-(0[1-9]|1[0-2])$/)))
});

export const zClearDeclarationPaymentResponse = zDeclarationsData;

export const zRecordDeclarationPaymentBody = zSummarizeDeclarationsData;

export const zRecordDeclarationPaymentPath = z.object({
    kind: z.int(),
    periodKey: z.string()
});

export const zRecordDeclarationPaymentResponse = zDeclarationsData;

export const zListDocumentLibraryResponse = zDocumentLibraryData;

export const zListExpensesQuery = z.object({
    month: z.nullish(z.string().check(z.regex(/^(19|20)\d{2}-(0[1-9]|1[0-2])$/)))
});

export const zListExpensesResponse = zExpensesMonthData;

export const zCreateExpenseBody = zExpenseInputData;

export const zCreateExpenseResponse = zExpensesMonthData;

export const zRecategorizeExpensesBody = zRecategorizeExpensesData;

export const zRecategorizeExpensesResponse = zExpensesMonthData;

export const zDeferExpensesVatBody = zExpenseSelectionData;

export const zDeferExpensesVatResponse = zExpensesMonthData;

export const zReintegrateExpenseVatPath = z.object({
    expense: z.int()
});

export const zReintegrateExpenseVatResponse = zExpensesMonthData;

export const zDeleteExpensePath = z.object({
    expense: z.int()
});

/**
 * No content
 */
export const zDeleteExpenseResponse = z.void();

export const zUpdateExpenseBody = zExpenseInputData;

export const zUpdateExpensePath = z.object({
    expense: z.int()
});

export const zUpdateExpenseResponse = zExpensesMonthData;

export const zUnlinkExpenseBankMovementPath = z.object({
    expense: z.int()
});

export const zUnlinkExpenseBankMovementResponse = zExpensesMonthData;

export const zLinkExpenseBankMovementBody = zLinkExpenseBankMovementData;

export const zLinkExpenseBankMovementPath = z.object({
    expense: z.int()
});

export const zLinkExpenseBankMovementResponse = zExpensesMonthData;

export const zDetachExpenseReceiptPath = z.object({
    expense: z.int()
});

export const zDetachExpenseReceiptResponse = zExpensesMonthData;

export const zDownloadExpenseReceiptPath = z.object({
    expense: z.int()
});

export const zDownloadExpenseReceiptResponse = z.string();

export const zAttachExpenseReceiptBody = zUploadExpenseReceiptData;

export const zAttachExpenseReceiptPath = z.object({
    expense: z.int()
});

export const zAttachExpenseReceiptResponse = zExpensesMonthData;

export const zShowInstanceResponse = zInstanceData;

export const zListInvoicesQuery = z.object({
    status: z.nullish(zInvoiceStatus),
    clientId: z.nullish(z.int()),
    missionId: z.nullish(z.int()),
    late: z.nullish(z.boolean()),
    from: z.nullish(z.iso.date()),
    to: z.nullish(z.iso.date()),
    cursor: z.nullish(z.string().check(z.maxLength(1024)))
});

export const zListInvoicesResponse = zInvoiceListData;

export const zCreateInvoiceBody = zCreateInvoiceData;

export const zCreateInvoiceResponse = zInvoiceDetailData;

export const zShowInvoiceSummaryQuery = z.object({
    month: z.nullish(z.string().check(z.regex(/^(19|20)\d{2}-(0[1-9]|1[0-2])$/)))
});

export const zShowInvoiceSummaryResponse = zInvoiceSummaryData;

export const zShowNextInvoiceNumberResponse = zNextInvoiceNumberData;

export const zDeleteInvoicePath = z.object({
    invoice: z.int()
});

/**
 * No content
 */
export const zDeleteInvoiceResponse = z.void();

export const zShowInvoicePath = z.object({
    invoice: z.int()
});

export const zShowInvoiceResponse = zInvoiceDetailData;

export const zUpdateInvoiceBody = zUpdateInvoiceData;

export const zUpdateInvoicePath = z.object({
    invoice: z.int()
});

export const zUpdateInvoiceResponse = zInvoiceDetailData;

export const zSendInvoiceBody = zSendInvoiceData;

export const zSendInvoicePath = z.object({
    invoice: z.int()
});

export const zSendInvoiceResponse = zInvoiceDetailData;

export const zPayInvoiceBody = zPayInvoiceData;

export const zPayInvoicePath = z.object({
    invoice: z.int()
});

export const zPayInvoiceResponse = zInvoiceDetailData;

export const zRemindInvoiceBody = zRemindInvoiceData;

export const zRemindInvoicePath = z.object({
    invoice: z.int()
});

export const zRemindInvoiceResponse = zInvoiceDetailData;

export const zCorrectInvoiceDatesBody = zCorrectInvoiceDatesData;

export const zCorrectInvoiceDatesPath = z.object({
    invoice: z.int()
});

export const zCorrectInvoiceDatesResponse = zInvoiceDetailData;

export const zDeleteInvoiceDocumentPath = z.object({
    invoice: z.int()
});

/**
 * No content
 */
export const zDeleteInvoiceDocumentResponse = z.void();

export const zDownloadInvoiceDocumentPath = z.object({
    invoice: z.int()
});

export const zDownloadInvoiceDocumentResponse = z.string();

export const zUploadInvoiceDocumentBody = zUploadInvoiceDocumentData;

export const zUploadInvoiceDocumentPath = z.object({
    invoice: z.int()
});

export const zUploadInvoiceDocumentResponse = zInvoiceDetailData;

export const zDeleteMissionPath = z.object({
    client: z.string(),
    mission: z.string()
});

/**
 * No content
 */
export const zDeleteMissionResponse = z.void();

export const zShowMissionPath = z.object({
    client: z.string(),
    mission: z.string()
});

export const zShowMissionResponse = zMissionData;

export const zUpdateMissionBody = zUpdateMissionData;

export const zUpdateMissionPath = z.object({
    client: z.string(),
    mission: z.string()
});

export const zUpdateMissionResponse = zMissionData;

export const zCreateMissionBody = zCreateMissionData;

export const zCreateMissionPath = z.object({
    client: z.string()
});

export const zCreateMissionResponse = zMissionData;

export const zListMissionDocumentsPath = z.object({
    client: z.string(),
    mission: z.string()
});

export const zListMissionDocumentsResponse = zDocumentListData;

export const zUploadMissionDocumentBody = zUploadDocumentData;

export const zUploadMissionDocumentPath = z.object({
    client: z.string(),
    mission: z.string()
});

export const zUploadMissionDocumentResponse = zDocumentData;

export const zDeleteMissionDocumentPath = z.object({
    client: z.string(),
    mission: z.string(),
    document: z.int()
});

/**
 * No content
 */
export const zDeleteMissionDocumentResponse = z.void();

export const zUpdateMissionDocumentBody = zUpdateDocumentData;

export const zUpdateMissionDocumentPath = z.object({
    client: z.string(),
    mission: z.string(),
    document: z.int()
});

export const zUpdateMissionDocumentResponse = zDocumentData;

export const zDownloadMissionDocumentPath = z.object({
    client: z.string(),
    mission: z.string(),
    document: z.int()
});

export const zDownloadMissionDocumentResponse = z.string();

export const zListMissionTimeEntriesPath = z.object({
    client: z.string(),
    mission: z.string()
});

export const zListMissionTimeEntriesResponse = zTimeEntryListData;

export const zPasskeyRegistrationOptionsResponse = zPasskeyOptionsData;

export const zRegisterPasskeyBody = zRegisterPasskeyData;

export const zRegisterPasskeyResponse = zPasskeyData;

export const zDeletePasskeyPath = z.object({
    passkey: z.int()
});

/**
 * No content
 */
export const zDeletePasskeyResponse = z.void();

export const zRenamePasskeyBody = zRenamePasskeyData;

export const zRenamePasskeyPath = z.object({
    passkey: z.int()
});

export const zRenamePasskeyResponse = zPasskeyData;

export const zPasskeyLoginOptionsResponse = zPasskeyOptionsData;

export const zLoginWithPasskeyBody = zPasskeyLoginData;

export const zLoginWithPasskeyResponse = zUserData;

export const zReadExpenseReceiptBody = zReadReceiptData;

export const zReadExpenseReceiptResponse = zReceiptSuggestionData;

export const zShowRecoveryCodesResponse = zRecoveryCodesData;

export const zRegenerateRecoveryCodesResponse = zRecoveryCodesData;

export const zShowRevenueQuery = z.object({
    period: z.nullish(z.string().check(z.regex(/^\d{4}(-(0[1-9]|1[0-2])|-Q[1-4])?$/))),
    basis: z.nullish(zRevenueBasis)
});

export const zShowRevenueResponse = zRevenueData;

export const zShowSettingsResponse = zSettingsData;

export const zUpdateSettingsBody = zUpdateSettingsData;

export const zUpdateSettingsResponse = zSettingsData;

export const zUpdateSettingsCurrencyBody = zUpdateSettingsCurrencyData;

export const zUpdateSettingsCurrencyResponse = zSettingsData;

export const zRefreshSettingsRatesResponse = zSettingsData;

/**
 * No content
 */
export const zDeleteUserSignatureResponse = z.void();

export const zShowUserSignatureResponse = z.string();

export const zUploadUserSignatureBody = zUploadSignatureData;

/**
 * No content
 */
export const zUploadUserSignatureResponse = z.void();

export const zListSubscriptionsResponse = zSubscriptionsData;

export const zCreateSubscriptionBody = zSubscriptionInputData;

export const zCreateSubscriptionResponse = zSubscriptionsData;

export const zDismissRecurringDebitBody = zDismissRecurringDebitData;

export const zDismissRecurringDebitResponse = zSubscriptionsData;

export const zDeleteSubscriptionPath = z.object({
    subscription: z.int()
});

/**
 * No content
 */
export const zDeleteSubscriptionResponse = z.void();

export const zUpdateSubscriptionBody = zSubscriptionInputData;

export const zUpdateSubscriptionPath = z.object({
    subscription: z.int()
});

export const zUpdateSubscriptionResponse = zSubscriptionsData;

export const zChangeSubscriptionAmountBody = zChangeSubscriptionAmountData;

export const zChangeSubscriptionAmountPath = z.object({
    subscription: z.int()
});

export const zChangeSubscriptionAmountResponse = zSubscriptionsData;

export const zResumeSubscriptionPath = z.object({
    subscription: z.int()
});

export const zResumeSubscriptionResponse = zSubscriptionsData;

export const zPauseSubscriptionPath = z.object({
    subscription: z.int()
});

export const zPauseSubscriptionResponse = zSubscriptionsData;

export const zReactivateSubscriptionPath = z.object({
    subscription: z.int()
});

export const zReactivateSubscriptionResponse = zSubscriptionsData;

export const zCancelSubscriptionBody = zCancelSubscriptionData;

export const zCancelSubscriptionPath = z.object({
    subscription: z.int()
});

export const zCancelSubscriptionResponse = zSubscriptionsData;

export const zListTimeEntriesQuery = z.object({
    from: z.iso.date(),
    to: z.iso.date()
});

export const zListTimeEntriesResponse = zTimeEntryListData;

export const zCreateTimeEntryBody = zTimeEntryInputData;

export const zCreateTimeEntryResponse = zTimeEntryData;

export const zSummarizeMonthWorkloadQuery = z.object({
    month: z.string().check(z.regex(/^(19|20)\d{2}-(0[1-9]|1[0-2])$/))
});

export const zSummarizeMonthWorkloadResponse = zMonthWorkloadData;

export const zDeleteTimeEntryPath = z.object({
    timeEntry: z.int()
});

/**
 * No content
 */
export const zDeleteTimeEntryResponse = z.void();

export const zUpdateTimeEntryBody = zTimeEntryInputData;

export const zUpdateTimeEntryPath = z.object({
    timeEntry: z.int()
});

export const zUpdateTimeEntryResponse = zTimeEntryData;

/**
 * No content
 */
export const zDiscardTimerResponse = z.void();

export const zShowTimerResponse = zTimerStateData;

export const zStartTimerBody = zStartTimerData;

export const zStartTimerResponse = zTimerData;

export const zUpdateTimerBody = zUpdateTimerData;

export const zUpdateTimerResponse = zTimerData;

export const zPauseTimerResponse = zTimerData;

export const zResumeTimerResponse = zTimerData;

export const zTrimTimerBody = zTrimTimerData;

export const zTrimTimerResponse = zTimerData;

export const zStopTimerBody = zStopTimerData;

export const zStopTimerResponse = zTimeEntryData;

/**
 * No content
 */
export const zDisableTotpResponse = z.void();

export const zStartTotpSetupResponse = zTotpSetupData;

export const zConfirmTotpBody = zConfirmTotpData;

export const zConfirmTotpResponse = zRecoveryCodesData;

export const zShowTreasuryResponse = zTreasuryData;

export const zCreatePersonalTransferBody = zCreatePersonalTransferData;

export const zCreatePersonalTransferResponse = zTreasuryData;

export const zDeletePersonalTransferPath = z.object({
    transfer: z.int()
});

export const zDeletePersonalTransferResponse = zTreasuryData;

/**
 * No content
 */
export const zRevokeAllTrustedDevicesResponse = z.void();

export const zRevokeTrustedDevicePath = z.object({
    trustedDevice: z.int()
});

/**
 * No content
 */
export const zRevokeTrustedDeviceResponse = z.void();

export const zShowTwoFactorResponse = zTwoFactorStatusData;

export const zAnswerTwoFactorChallengeBody = zTwoFactorChallengeAnswerData;

export const zAnswerTwoFactorChallengeResponse = zUserData;

export const zTwoFactorPasskeyOptionsResponse = zPasskeyOptionsData;

export const zListUserDocumentsResponse = zDocumentListData;

export const zUploadUserDocumentBody = zUploadDocumentData;

export const zUploadUserDocumentResponse = zDocumentData;

export const zDeleteUserDocumentPath = z.object({
    document: z.int()
});

/**
 * No content
 */
export const zDeleteUserDocumentResponse = z.void();

export const zUpdateUserDocumentBody = zUpdateDocumentData;

export const zUpdateUserDocumentPath = z.object({
    document: z.int()
});

export const zUpdateUserDocumentResponse = zDocumentData;

export const zDownloadUserDocumentPath = z.object({
    document: z.int()
});

export const zDownloadUserDocumentResponse = z.string();
